### ISSUE TITLE
GPU implementation request cuda

### ISSUE THREAD

**Issue by nft30001** [Noname400/Hunt-to-Mnemonic#1]
Can you please compile this for GPU cuda for windows

**Comment by Noname400** [comment]
Это следующий этап

**Comment by roi35** [comment]
Посмотрите на этот проект на гитхабе. Может получится переделать под бтц или ефир… было б круто github.com/Rexagon/ton-address-miner

**Comment by Noname400** [comment]
этот проект не подойдет.
всему свое время.
сейчас надо закончить версию с HASH160
и доделать сервер клиент.
после этого займусь GPU
это не так быстро как Вы себе представляете и требует массу времени которого маловато.
