### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by VuzzyM** [Noname400/Hunt-to-Mnemonic#10]
Нужно ли нам создавать файл result.txt рядом с PulsarMT2-hash.py?  ранее был файл rezult.txt

для чего нужен файл funcP.py?

**Comment by Noname400** [comment]
файл результатов создается автоматически
я переписываю сейчас код программы с нуля.
самые нужные функции вынес в отдельный модуль funcP.py

**Comment by Noname400** [comment]
сейчас заливаю на гугл новые базы
также рекомендую их обновить и сегодня выложу новую бету
