### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by PDOGEDEV** [Noname400/Hunt-to-Mnemonic#11]
Could you write a code that takes a textfile with 12 word seeds and returns an output with all hex addresses?

**Comment by Noname400** [comment]
какой BIP ? 44, 32, 49 ?

**Comment by PDOGEDEV** [comment]
It would be nice if all potential addresses and keys could be derived from a long list .txt of 12 word seeds

**Comment by Noname400** [comment]
адрес должен начинаться на 1 или 3

**Comment by Noname400** [comment]
или bc1

**Comment by PDOGEDEV** [comment]
I have a long list of pre generated 12 seed words (not all valid) that I would like to check quickly, generate the adress and check in bloom filter.

I am looking in to this because I want a quicker way to check seeds

**Comment by Noname400** [comment]
вы понимаете что одна мнемоника это 2147483648 адресов
не считая жестких адресов которые еще + 2147483648

**Comment by PDOGEDEV** [comment]
Could you please implement one of the following?:

A. An option to override bip official wordlist with an input for a custom wordlist like -i wordlist.txt

or

B. An option to input a text file with pre generated 12 words instead of generating on the go, like -i 12words.txt

I would greatly appreciate this.
