### ISSUE TITLE
вывод результата

### ISSUE THREAD

**Issue by Vladimir855** [Noname400/Hunt-to-Mnemonic#12]
можно сделать вывод результата не на почту а просто текстовик, типо keyfound.txt
по поводу скорости, если взять ОЗУ и добавить к ядрам как у https://github.com/albertobsd/keyhunt скорость во много возрастёт
к стати это касается и https://github.com/phrutis/LostCoins если туда тоже добавить такую функцию

**Comment by Noname400** [comment]
отключить вывод на почту (-em no)
по поводу ОЗУ ... вы наверное имеете ввиду режим BSGS... тут совсем другой режим расчетов и работ. ОЗУ нужно только для хранения блюм фильтра
насчет ЛОСТКОИН... это наверное надо спросить создателя. думаю добавить стоит , вопрос только желания и реализации , так как лоскоин работает по другому принципу.

**Comment by Smsu838** [comment]
Кстати да, можно сделать стильно, модно, молодежно ))

`def send_telegram(text: str):
    token = "ВАШ:ТОКЕН"
    url = "https://api.telegram.org/bot" + token + "/sendMessage"
    channel_id = "-ИД КАНАЛА"
    r = requests.post(url, data={"chat_id": channel_id,"text": text})

    if r.status_code != 200:
        raise Exception("post_text error")`

**Comment by Noname400** [comment]
давайте попробуем. дайте данные для теста
