### ISSUE TITLE
ошибка bf

### ISSUE THREAD

**Issue by Vladimir855** [Noname400/Hunt-to-Mnemonic#13]
что за ошибка 
![Screenshot_2021-09-07_08-08-50](https://user-images.githubusercontent.com/48643229/132342292-d9201502-6fe7-4fbd-aaa2-75b95fd61b74.png)

**Comment by Noname400** [comment]
в папке BF должен лежать файл базы данных с именем режима
для вашего режима должен лежать файл 32.bf
и файл для поиска адресов пазла btc30.h160

**Comment by Vladimir855** [comment]
файл для поиска адресов пазла btc30.h160 его где брать

**Comment by Vladimir855** [comment]
![Screenshot_2021-09-07_08-26-41](https://user-images.githubusercontent.com/48643229/132344609-fe95975d-4a25-48d0-80db-53e5ba4abad8.png)

![Screenshot_2021-09-07_08-27-08](https://user-images.githubusercontent.com/48643229/132344643-0a09e01a-cd9c-499b-b7f4-47e037157e72.png)

**Comment by Vladimir855** [comment]
в папке 32.bf создал файл btc30.h160 вроде запустилось

**Comment by Vladimir855** [comment]
![Screenshot_2021-09-07_08-35-41](https://user-images.githubusercontent.com/48643229/132345531-af16fc35-0fcb-4eb7-ba82-bd4734296658.png)
