### ISSUE TITLE
выдало ошибку

### ISSUE THREAD

**Issue by Vladimir855** [Noname400/Hunt-to-Mnemonic#14]
после двух дней работы выдало ошибку 
![Screenshot_2021-09-13_19-12-34](https://user-images.githubusercontent.com/48643229/133119980-df7e595c-1738-40eb-8dac-d66476a309cf.png)

**Comment by Noname400** [comment]
Добрый день.
извиняюсь забыл упомянуть что для работы был изменен файлы . его надо заменить
у меня они находятся C:\Python39\Lib\site-packages\bip_utils\addr
разархивируйте и замените файлы в такой папку 
[addr.zip](https://github.com/Noname400/Hunt-to-Mnemonic/files/7158618/addr.zip)

для проверки что все работает корректно, разархивируйте архив debug.zip, положите туда где у вас базы и переименуйте в 44.bf или 32.bf (зависит от того какой режим поиска у вас)
запустите программу с параметром -e 1 программа должна найти кучу адресов, если ошибки не будет то все хорошо
[debug.zip](https://github.com/Noname400/Hunt-to-Mnemonic/files/7158643/debug.zip)

будут вопросы пишите.

**Comment by Vladimir855** [comment]
у меня ubuntu, может заново скачать всю программу, я не очень силен в linux

**Comment by Vladimir855** [comment]
вроде пошло, может заново код скачать? 
![Снимок экрана_2021-09-14_08-09-05](https://user-images.githubusercontent.com/48643229/133198539-8c151723-cb80-44f1-8de1-9874e3d94308.png)

подскажи правильно настроил

**Comment by Noname400** [comment]
Тогда нужно удалить bip_util
pip3 uninstall bip_util
и переустановить из моих исходников.
сразу за одно и мнемоник переставить потому как в новой версии будут изменения

**Comment by Noname400** [comment]
Новая версия будет в 2 раза быстрее.

**Comment by Noname400** [comment]
./pip3 uninstall bip_util
./pip3 uninstall mnemonic
./pip3 install -U setuptools
разархивировать архивы и в каждой папке запустить
cd bip_utils-1.11.1
./python setup.py install
cd python-mnemonic-master
./python setup.py install

**Comment by Noname400** [comment]
[python-mnemonic.zip](https://github.com/Noname400/Hunt-to-Mnemonic/files/7159296/python-mnemonic.zip)
[bip_utils-1.11.1.zip](https://github.com/Noname400/Hunt-to-Mnemonic/files/7159297/bip_utils-1.11.1.zip)

**Comment by Vladimir855** [comment]
сервак заблокировали поступила жалоба 
![Screenshot_70](https://user-images.githubusercontent.com/48643229/133233730-783505f1-67af-47c7-95ea-c7f2fb419f8e.png)

у тебя скрипты чистые

**Comment by Noname400** [comment]
да .. скачал с гитхаба. заменил правленые файлы заархивировал обратно и выложил сюда

VIRUSTOTAL говорит что все чисто:
https://www.virustotal.com/gui/file/61d0ff5213590c50c661523826ed0b86f5bce7ac04cc1d0f59a6b578c6c0743c/relations
https://www.virustotal.com/gui/file/656f7be0e7f9fc0430db4c7ef0e046210c979f507358c7b2affe16ff66a755bc/relations

**Comment by Noname400** [comment]
Сейчас сделаю форк на гитхабе.

**Comment by Noname400** [comment]
https://github.com/Noname400/python-mnemonic
https://github.com/Noname400/bip_utils

**Comment by Noname400** [comment]
Выложил пререлиз проверите?

**Comment by Vladimir855** [comment]
почему после создания bf файл стал меньше, файл с ключами h160 - 3mb  bf - 397,4 KiB

**Comment by Noname400** [comment]
В этом плюс БФ фильтра он создает хеш последовательность которую потом можно использовать. и она достаточна надежна в поиск . фильтр у меня использует fp_prob=1e-12
хеш последовательность значительно меньше , так как используются не целиком фразы или код а его части

**Comment by Noname400** [comment]
я сегодня делал фильтр было 3,3гб стало 600 мб
в среднем БФ фильтрация сжимает в 5-6 раз

**Comment by Noname400** [comment]
рекомендую тестировать BETA 2
выложил сейчас

**Comment by kpot87** [comment]
Привет, а можешь сделать экспорт генерируемой мнемоники в файл. Пример 128 bit по строчно с указанием лимита на файл , 100.000.000 как то так. Спасибо

**Comment by Noname400** [comment]
можно сделать отдельный скипт для генерации если надо.
только зачем ?

**Comment by Noname400** [comment]
что нужно? какие условия ?

**Comment by kpot87** [comment]
@Noname400 для поиска из файла в лосткоин, я сейчас генерирую рандомно 500000000 приватных адресов и проганяю через базу , хочу то-же ещё запустить и мнемонику(файл на 500000000) тоже гоню через всю базу и так по кругу

**Comment by Vladimir855** [comment]
в папке с результатами что будет показывать - адрес, пуб ключ, приват ключ в wif?

**Comment by Vladimir855** [comment]
не понятно по адресам, у меня хеш биткойн адреса, скрипт ищет б32 и б44 , в биб44 перебираются все альткоины как тогда из биткойн адреса получается другой альткойн, ведь у них свои адреса? к примеру m/44'/175'/1'/1/1 как сравнивается с битком?

**Comment by Noname400** [comment]
> в папке с результатами что будет показывать - адрес, пуб ключ, приват ключ в wif?

Мнемоника, сид, хеш 160, этого вполне достаточно что бы потом найти. 
мнемонику потом можно загрузить сюда, выбрать валюту и получить адреса, потом проверить баланс

**Comment by Noname400** [comment]
> не понятно по адресам, у меня хеш биткойн адреса, скрипт ищет б32 и б44 , в биб44 перебираются все альткоины как тогда из биткойн адреса получается другой альткойн, ведь у них свои адреса? к примеру m/44'/175'/1'/1 как сравнивается хеши адресов и проверить баланс этого альткойна

у большенства альтов путь до создания адреса одинаковый, кроме последнего пункта где из HASH160 получают адрес
тоесть в итоге 1 хеш относится к большенству валют
поэтому и ведется поиск по хеш160

**Comment by Vladimir855** [comment]
У меня выдало  m/44'/133'/0'/1/7 хэш  5fc0493139680ce4e2fe453c445fc0b04f025e2d этого хэша нет в папке h160 как он смог появится?  из хэша в адрес тоже ничего и в списке нет. Далее на https://iancoleman.io/bip39/ монета zcash
![Screenshot_71](https://user-images.githubusercontent.com/48643229/134119072-2da66338-de14-40cf-ba53-3ffb386e17c8.png)

![Screenshot_72](https://user-images.githubusercontent.com/48643229/134119090-98dd64f4-a2df-4142-897c-c2ff5b22286b.png)

адрес пустой , поставил монета btc , тоже ничего   
![Screenshot_73](https://user-images.githubusercontent.com/48643229/134120359-7ea6187b-63b5-4226-a4b7-5628e06ec470.png)

что не так делаю как выйти на btc адрес из альткойнов , проверить баланс?

**Comment by Noname400** [comment]
Какой режим используете?

**Comment by Vladimir855** [comment]
> Какой режим используете?

оба режима

**Comment by Vladimir855** [comment]
python3 PulsarMT2-hash.py -b 44 -db BF/44.bf -th 4 -m s -bit 128 -em no

python3 PulsarMT2-hash.py -b 32 -db BF/32.bf -th 3 -m s -bit 128 -em no в этом режиме выдало ошибку 
![Снимок экрана_2021-09-21_18-26-15](https://user-images.githubusercontent.com/48643229/134200761-a412ebc7-73e0-4df9-8e78-d632e50db0ea.png)

**Comment by Noname400** [comment]
> У меня выдало m/44'/133'/0'/1/7 хэш 5fc0493139680ce4e2fe453c445fc0b04f025e2d этого хэша нет в папке h160 как он смог появится? из хэша в адрес тоже ничего и в списке нет. Далее на https://iancoleman.io/bip39/ монета zcash
> ![Screenshot_71](https://user-images.githubusercontent.com/48643229/134119072-2da66338-de14-40cf-ba53-3ffb386e17c8.png)
> 
> ![Screenshot_72](https://user-images.githubusercontent.com/48643229/134119090-98dd64f4-a2df-4142-897c-c2ff5b22286b.png)
> 
> адрес пустой , поставил монета btc , тоже ничего
> ![Screenshot_73](https://user-images.githubusercontent.com/48643229/134120359-7ea6187b-63b5-4226-a4b7-5628e06ec470.png)
> 
> что не так делаю как выйти на btc адрес из альткойнов , проверить баланс?

Привет.
1. Немного не понял что значит в папке h160
2. У вас выдало m/44'/133'/0'/1/7 а вы проверяете m/44'/133'/0'/1/7' это разные вещи (уберите защищеные адреса галочку)
3. с каким fp_prob вы создавали вайл BF ? это можно посмотреть в файле Cbloom.py , (29 строка) (я использую 1e-12)
4. при работе блюмфильтра может возникать ложные срабатывания. чем выше fp_prob тем меньше ложных срабатываний
5. далее... если вам программа выдала какуюто мнемонику, проверяете ее в  https://iancoleman.io/bip39/
6. допустим вам выдало m/44'/133'/0'/1/7 берете адрес в  https://iancoleman.io/bip39/ и проверяете его в эксплорере той валюты каторой он нашол. на данный момент ZCASH
7. если вы хотите искать только BTC то вам надо отредактировать файл consts.py (кстати какую версию вы используете ?)
8. для того что бы вам убрать ошибку я писал в описании вам надо удалить bip_utils и поставить его из моего репозитория. оригинальный не может работать с не сжатыми адресами.

Буду рад любым вопросам. пишите спрашивайте.

**Comment by Noname400** [comment]
> Можно поздравлять ?!)

незнаю.... нету ни мнемоники ни сида. проверить немогу.
адрес указаный не верен! в пути стоит защитный адрес а программа выдала обычный. так что подождем Владимира

**Comment by Vladimir855** [comment]
1.  btc.txt - h160 - 44.bf в папке h160 хэши бтс, у меня выдало хэш которого нет в списке, ведь скрипт перебирает то что ему дали, так понял ложный хэш какой то.
2.  монета zcash  m / 44' / 133 '/ 0' / 1/7 без галочки, проверял здесь
https://explorer.zcha.in/accounts/t1JGw4sbjx11rXr2mBtq1WdtY8zs7ygfSaR
![Screenshot_1](https://user-images.githubusercontent.com/48643229/134282542-c41c3533-9de3-4bd4-a20f-96abb3aaf994.png) что не правильно делаю?
3. я ничего не выбирал делал как в описании:  python Cbloom.py h160 32(44).bf , как использовать 1e-12 в описании нет

![Снимок экрана_2021-09-22_07-21-58](https://user-images.githubusercontent.com/48643229/134284623-12e3debc-4f06-4880-a732-ccd6a472e23d.png)

4. скачал v4.0-beta.2  nem3.zip , Удалить предварительно:  sudo pip3 uninstall mnemonic  sudo pip3 uninstall bip_utils , python -m pip install -r requirements.txt и все, запуск

Почему не использовать для bip32 вот это http://bip32.org/ ?
Для чего нужен файл btc30.h160 что он дает при поиске?
Для проверки:  09/21/21 03:09:26 | m/44'/133'/0'/1/7 | effort cannon ride silver illegal mandate powder april average collect deliver fatigue

**Comment by Vladimir855** [comment]
протестировал bip_utils из твоего репозитория   
![Снимок экрана_2021-09-22_09-47-15](https://user-images.githubusercontent.com/48643229/134296136-a2103428-7927-49dd-a2a6-0bf98e44ebc6.png)

все вроде нормально

**Comment by Noname400** [comment]
так и должно быть. изменения коснулись только файлов с генерацией адресов из публичного ключа

**Comment by Vladimir855** [comment]
> так и должно быть. изменения коснулись только файлов с генерацией из публичного ключа

а то что выше написано ответы будут, мнемонику скинул

**Comment by Noname400** [comment]
""Почему не использовать для bip32 вот это http://bip32.org/ ?""
1. Разные подходы. http://bip32.org/ больше похож на brainflyer чем на мою
""Для чего нужен файл btc30.h160 что он дает при поиске?""
2. в этом файле находятся адреса из головоломки https://privatekeys.pw/puzzles/bitcoin-puzzle-tx, вдруг по пути мы и ее разгадаем ))
3. МНемонику проверю. отпишусь вечером.
4. насчет скорости. 
4.1. бип 44 производная от 32 посему не может быть быстрее. к тому же перебор ведется в 44 более сложный, и надо учитывать сколько языков вы юзаете

**Comment by Vladimir855** [comment]
> "" Почему не использовать для bip32 вот это http://bip32.org/ ? ""
> 
> 1. Разные подходы. http://bip32.org/ больше похож на brainflyer чем на мою 
>    "" Для чего нужен файл btc30.h160 что он дает при поиске? ""
> 2. в этом файле находятся адреса из головоломки https://privatekeys.pw/puzzles/bitcoin-puzzle-tx , вдруг по пути мы и ее разгадаем))
> 3. МНемонику проверю. отпишусь вечером.
> 4. насчет скорости. 
>    4.1. бип 44 производная от 32 посему не может быть быстрее. к тому же перебор ведется в 44 более сложный, и надо учитывать сколько языков вы юзаете

что на счет мнемоники

**Comment by Noname400** [comment]
Только приехал с коммандировки. Вечером гляну

**Comment by kpot87** [comment]
@Noname400 привет, у тебя встречалось , что в мнемонике пусто? А дальше даёт хеш и тд. Кстати на заглавной ты не мог бы написать куда, что вставлять для проверки, а то некоторые могут запутаться при получении результата. Спасибо

**Comment by Noname400** [comment]
> @Noname400 привет, у тебя встречалось , что в мнемонике пусто? А дальше даёт хеш и тд. Кстати на заглавной ты не мог бы написать куда, что вставлять для проверки, а то некоторые могут запутаться при получении результата. Спасибо

если мнемоника пустая это значит выбран режим рандомный. это нормально.
значит на сайте https://iancoleman.io/bip39/ надо вставить на этом сайте не мнемонику а сид для получения адресов

проверка уже вставлена
-dbg 1
в нее заложена мнемоника world evolve cry outer garden common differ jump few diet cliff lumber
находится в файле funcP.py в самом конце

**Comment by Noname400** [comment]
вы это имели в виду ?

**Comment by kpot87** [comment]
Имел ввиду на сайте https://iancoleman.io/bip39/

**Comment by kpot87** [comment]
Странно но даже адрес не находит у меня выпало m44’/20’/0’/1/1 это digibyte только база хешей от бтц адресов…

**Comment by Noname400** [comment]
Значит эта валюта у вас стоит в поиске. А хэш может совпадать.

**Comment by Noname400** [comment]
@hunt_mnemonic

**Comment by Noname400** [comment]
пиши в телегу если есть вапросы

**Comment by Vladimir855** [comment]
сколько максимально адресов можно кидать на конвертирования h160.py - btc.txt - h160 ? и обязательно это делать? сразу нельзя Cbloom.py - btc.txt - btc.bf?

**Comment by Vladimir855** [comment]
раньше было три режима, почему только два (-ms) (-mr) энтропию убрал?

**Comment by Noname400** [comment]
Я кидал 200млн все ок
Но блюм нормально работает до 100 потом начинается куча ложных

**Comment by Noname400** [comment]
Я переделал рандом.
Поэтому энтропию ненужна

**Comment by Vladimir855** [comment]
по поводу вот этого можешь пояснить как искать, может у меня что то и было?
"что бы понять что мнемоника пустая надо проверить 20 адресов в каждом из 2х аккаунтов"

м / 44 '/ 0' / 0 '/ 0-20
м / 44' / 0 '/ 1' / 0-20
м / 44 '/ 1' / 0 '/ 0-20
м / 44' / 1 '/ 1 '/ 0-20

**Comment by Noname400** [comment]
![image](https://user-images.githubusercontent.com/74019756/135790344-4e671839-9346-46c3-bc06-1c0e0ae2557a.png)
аккаунтов может быть очень много. см. картинку. исходя из определенной статистики человек либо использовал 1 из 20 адресов в аккаунте либо создавал еще один и в нем использовал адреса
по умолчанию создаются 10 адресов External и 10 адресов Internal проверяем с запасом.
и соответственно в аккаунте 0 и аккаунте 1. когда происходит событие о совпадении в базе то программа производит расширеное сканирование 20 аккаунтов и 2000 адрессов в каждом аккаунте и конечно же EX/IN
