### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by PDOGEDEV** [Noname400/Hunt-to-Mnemonic#15]
Hi,

Very happy to see you update the code.

I am having issues, can you help?

PulsarMT2-hash.py: error: argument -t/--threading: invalid int value: 'h'

**Comment by Noname400** [comment]
Screen please.

**Comment by Noname400** [comment]
python3 PulsarMT2-hash.py -b 32 -db BF/work.bf -dbp BF/btc30.h160 -th 2 -des source -m s -bit 128 -em no -sc no

**Comment by Noname400** [comment]
-th 2

**Comment by Noname400** [comment]
Delete old file and folder
Create new folder
Unzip
Work.

**Comment by PDOGEDEV** [comment]
I dont have a screenshot right now, but the -db command did not work, only -d worked and dpb is not recognized at all.

I unzipped everything to a new folder and also did the required uninstalling and then installing from your project.

I am using powershell in windows

**Comment by PDOGEDEV** [comment]
I did not delete old folder, just made a new one. Is deleting old folder neccesary?

**Comment by Noname400** [comment]
-d this  old version

**Comment by PDOGEDEV** [comment]
So how can I get new version installed?

**Comment by Noname400** [comment]
https://github.com/Noname400/Hunt-to-Mnemonic/releases/tag/v4.0.b2

**Comment by PDOGEDEV** [comment]
Hi,

Now I have this issue:

ModuleNotFoundError: No module named 'include.funcP'

**Comment by Noname400** [comment]
Unzip new folder

**Comment by Noname400** [comment]
> Hi,
> 
> Now I have this issue:
> 
> ModuleNotFoundError: No module named 'include.funcP'

This old version

**Comment by PDOGEDEV** [comment]
Hmm ok, but I have downloaded the latest version and created a new folder already?

**Comment by Noname400** [comment]
Момент, я подготовлю новый репозиторий

**Comment by PDOGEDEV** [comment]
Thanks for amazing support

**Comment by PDOGEDEV** [comment]
I see you updated now, should I try again?

**Comment by Noname400** [comment]
Please take your time.  I haven't finished updating.

**Comment by Noname400** [comment]
I'll finish it tomorrow.  I will increase the speed and stability of work

**Comment by PDOGEDEV** [comment]
Any news?

**Comment by Noname400** [comment]
Можно проверять.

**Comment by Noname400** [comment]
@hunt_mnemonic

**Comment by Noname400** [comment]
пиши в телегу если есть вапросы

**Comment by PDOGEDEV** [comment]
python PulsarMTv4.py -b 32 -db BF/work.bf -dbp BF/btc30.h160 -th 2 -des source -m s -bit 128 -em no -sc no

**Comment by PDOGEDEV** [comment]
What bloom file should I use? Can I use the old ones?

**Comment by PDOGEDEV** [comment]
You need to update the readme too, it does not have the new PulsarMTv4.py name in example

**Comment by PDOGEDEV** [comment]
and what is work.bf? that file does not exist among the old bloomfiles

**Comment by PDOGEDEV** [comment]
If I want to to only eth, then this is ok?
python PulsarMTv4.py -b ETH -db c:\hunt\bf\eth.bf -th 24 -m s -bit 128 -em no -sc no

**Comment by PDOGEDEV** [comment]
Also, eth is slower because more addresses right?

**Comment by Noname400** [comment]
> Какой файл bloom мне использовать? Могу я использовать старые?

Yes

**Comment by Noname400** [comment]
> Вам также необходимо обновить файл readme, в примере нет нового имени PulsarMTv4.py

Я обновлю. Дайте время.

**Comment by Noname400** [comment]
> а что такое work.bf? этот файл не существует среди старых bloomfiles

Это мой файл для bip44

**Comment by Noname400** [comment]
> Если я хочу использовать только eth, тогда это нормально?
> python PulsarMTv4.py -b ETH -db c: \ hunt \ bf \ eth.bf -th 24 -ms -bit 128 -em no -sc нет

Это правильно. Я завтра обновлю ETH.  Думаю скорость будет выше.

**Comment by Noname400** [comment]
> Кроме того, eth медленнее, потому что больше адресов, верно?

И да и нет.))))

**Comment by PDOGEDEV** [comment]
So eth is slower for other reasona too that you will update tomorrow? sounds good, thanks :)

**Comment by PDOGEDEV** [comment]
My Friend, I see you are working hard. Did you update the Eth work? should I download and update?

**Comment by Noname400** [comment]
> Мой друг, я вижу, ты много работаешь. Вы обновили работу Eth? мне скачать и обновить?

да. я бы хотел что бы вы протестировали текущую версию

**Comment by PDOGEDEV** [comment]
Thanks, I will try very soon.

I get many false positives, would it be possible to add an automatic balance check on etherscan?

**Comment by Noname400** [comment]
> Спасибо, очень скоро попробую.
> 
> У меня много ложных срабатываний, можно ли добавить автоматическую проверку баланса на etherscan?

Вы давно создавали базу ?
если более 2х недель назад., рекомендую скачать снова файл Cbloom.py и создать базу снова это уберет много лишних срабатываний. 
да я планируют позже добавить проверку баланса

**Comment by PDOGEDEV** [comment]
It is a long time ago，I use your files. can you explain what i should do with cbloom file?

**Comment by Noname400** [comment]
python Cbloom.py eth.txt eth.bf
eth.txt - файл с адресами (формат 0xc0dfa494C655CEd70DB9184F1a06950058E1fef7 )
один адрес на одну строку

файл старый удалите. новый скачайте из моего репозитория.
файл eth.bf - получится немного больше чем был до этого

**Comment by PDOGEDEV** [comment]
I downloaded your bloom files so I dont have a eth.txt, can you share a new eth.txt or eth.bf that I can download?

**Comment by Noname400** [comment]
https://drive.google.com/drive/folders/1oBMNxqwyYqp6Dx1q5j6erajf9wahGAda?usp=sharing
через 15 минут архив закачается

**Comment by PDOGEDEV** [comment]
New version is 50% quicker

**Comment by Noname400** [comment]
это хорошо. надеюсь еще смогу поднять

**Comment by Noname400** [comment]
Вчера выложил. Проверку чуть позже. Сейчас отладка рескана

**Comment by PDOGEDEV** [comment]
I could only start this one: Pulsar v4.5b

Speed is about the same as before.
I am running eth.bf that I downloaded before. Is there anything else I need to update or change?

**Comment by PDOGEDEV** [comment]
I need some help:

----------------------------------------------------------------------
DEPENDENCY TESTING:
 ERROR: Generate mnemonic
 Please reinstall https://github.com/Noname400/mnemonic-for-hunt


I dont know how to install this: 

pip install mnemonic-0.20-py3-none-any.whl
    если не хотите устонавливать пакет, то добро пожаловать в репозиторий https://github.com/Noname400/mnemonic-for-hunt

PS C:\j10> pip install https://github.com/noname400/hunt-for-mnemonic
Collecting https://github.com/noname400/hunt-for-mnemonic
  ERROR: HTTP error 404 while getting https://github.com/noname400/hunt-for-mnemonic
ERROR: Could not install requirement https://github.com/noname400/hunt-for-mnemonic because of HTTP error 404 Client Err
or: Not Found for url: https://github.com/noname400/hunt-for-mnemonic for URL https://github.com/noname400/hunt-for-mnem

**Comment by mEloncoin** [comment]
No problem, I found the package and installed it
