### ISSUE TITLE
Пара вопросов по использованию.

### ISSUE THREAD

**Issue by 5taY3r** [Noname400/Hunt-to-Mnemonic#18]
Приветствую! В первую очередь хотел бы выразить благодарность за Вашу работу. Спасибо.
1. Есть ли смысл использовать другие пути, отличные от m/44'/0'/0'/0? Ведь большинство валетов его используют по умолчанию.
2. Почему мы ищем только в BIP32/BIP44? Не хватает проверки результатов в BIP49 и BIP84. Конвертится в hash160 любой адрес, следовательно и их можно подбирать, не выкидывая кучи адресов с балансом.
3. Bloomfiltr. Отдельная песня) При тестах находил 8/10, иногда находил то, чего нет. Слишком большие потери при его использовании и какая-то нестабильность в работе. Его бы заменить на что-то или искать по хешам выгрузив их память.
Пока как-то так. Буду дальше гонять.

**Comment by 5taY3r** [comment]
Ещё раз добрый день. Мнемоники сгенерированные программой не бьются на [https://iancoleman.io/bip39/](url)   -- tobacco space ball bottom outer anxiety celery clay lucky park orange pond --
К примеру, мнемоники сгенерированные BTCKeygen [https://github.com/modood/btckeygen](url) проходят проверку. В чём может быть причина и как это поправить?
![Screenshot_2021-11-02_05_30_04](https://user-images.githubusercontent.com/90869498/139822113-79d62c61-d739-4703-809e-79ba00da894d.png)

**Comment by Noname400** [comment]
какой режим

**Comment by 5taY3r** [comment]
В режиме r2.
В режиме s подтягивает все словари, пришлось подправить `

mnemo:Mnemonic = Mnemonic('english')
#mnemo:Mnemonic = Mnemonic(mem)
mnemonic:str = mnemo.generate(strength=inf.bit)
seed_bytes:bytes = mnemo.to_seed(mnemonic, passphrase='')`

Так проверку на BIP39 проходит

**Comment by Noname400** [comment]
у вас какой мнемоник стоит?

**Comment by 5taY3r** [comment]
> у вас какой мнемоник стоит?

mnemonic-0.20

**Comment by Noname400** [comment]
Родная или моя?

**Comment by 5taY3r** [comment]
Устанавливал с репозитория `sudo pip3 install mnemonic`

**Comment by Noname400** [comment]
поэтому и не сходится

**Comment by Noname400** [comment]
в папке install лежит инсталятор мнемоники
pip install mnemonic-0.20-py3-none-any.whl
