### ISSUE TITLE
Настройка

### ISSUE THREAD

**Issue by Vladimir855** [Noname400/Hunt-to-Mnemonic#20]
Noname400  Посмотри правильно настроил, может что то добавить надо? К стати спасибо что вернул работа со словами (3, 6, 9, 12, 15, 18, 21, 24) очень нужная штука. Хотел узнать, как определить сколько всего мнемоник должно быть, к примеру 2048 в 3 степени =8589934592 - это правильно вычитаю?

![Screenshot_2021-11-02_11-55-33](https://user-images.githubusercontent.com/48643229/139816588-18861d93-63f5-4a5f-b7e0-b0d65cb77277.png)

**Comment by Smsu838** [comment]
![132096498-db7fc3db-c50a-45c7-804e-48e0b3b3ddae](https://user-images.githubusercontent.com/83470911/140162242-f0dbdb26-5df8-4985-992f-00603702a724.jpg)

**Comment by Vladimir855** [comment]
откуда взял ссылку на источник можешь дать

**Comment by Smsu838** [comment]
Неа нашел когда то а где не помню

**Comment by Noname400** [comment]
> Noname400 Посмотри правильно настроил, может что то добавить надо? К стати спасибо что вернул работа со словами (3, 6, 9, 12, 15, 18, 21, 24) очень нужная штука. Хотел узнать, как определить сколько всего мнемоник должно быть, к примеру 2048 в 3 степени =8589934592 - это правильно вычитаю?
> 
> ![Screenshot_2021-11-02_11-55-33](https://user-images.githubusercontent.com/48643229/139816588-18861d93-63f5-4a5f-b7e0-b0d65cb77277.png)

с настройками все верно.
не забывайте проверять как все работает с -dbg 2

**Comment by Vladimir855** [comment]
Спасибо, добавлю -dbg 2

**Comment by Noname400** [comment]
Что вы хотите с ним сделать?

**Comment by Vladimir855** [comment]
> Что вы хотите с ним сделать?

отредактировать по балансу и в bf

**Comment by Vladimir855** [comment]
вижу были изменения с bip44 заново скачать репоз.

**Comment by Noname400** [comment]
Изменения не критичны.
Можно обновить только файл funcp

Что бы открыть используй emediror

**Comment by Noname400** [comment]
Он откроет даже если мамяти иало

**Comment by Vladimir855** [comment]
> Он откроет даже если мамяти иало

я им пробовал много раз вылетает пишет нехватка памяти, у меня 2 озу  ставил виртуальную память подкачки 3гб всё равно вылетает. может есть онлайн редактор, в гугле лазил ничего путнего не нашел

**Comment by Noname400** [comment]
Ставь подкачку 10гб

**Comment by roi35** [comment]
@Noname400  А какой свежести та база что у тебя на гугл диске? там только адреса в блюмфильтре на 1 и на 3 ? почему тогда она весит целых аж почти 600 мб? у меня база где хоть какой-то баланс плюс в блюм фильтре (через твои скрипты) весит недостигая 300 мб всего

**Comment by Noname400** [comment]
Базе месяц всего
почему столько весит.... там все адреса. вот и все ничего лишнего и коэфициэнт 12

**Comment by Vladimir855** [comment]
С эфиром ошибка, после запуска работает не долго и останавливается

![Screenshot_2021-12-18_14-42-44](https://user-images.githubusercontent.com/48643229/146639817-6041044b-1946-437f-b2b9-0abe2eb91ea3.png)

**Comment by Noname400** [comment]
Привет, другие режимы пробовали? Там также?

**Comment by Vladimir855** [comment]
> Привет, другие режимы пробовали? Там также?
работает два режима  В44 и eth, запускаю с разных папок (разархив. и эту же папку скопировал), режим btc работает. Три дня подряд эфир вылетает, каждое утро заново запускаю, пробовал в разных вариациях и рандомы менял и sl 5 убирал. На эфире будет показывать баланс?

**Comment by Noname400** [comment]
> > Привет, другие режимы пробовали? Там также?
> > работает два режима  В44 и eth, запускаю с разных папок (разархив. и эту же папку скопировал), режим btc работает. Три дня подряд эфир вылетает, каждое утро заново запускаю, пробовал в разных вариациях и рандомы менял и sl 5 убирал. На эфире будет показывать баланс?

я проверю и отпишусь . эфир единственное что давно не обновлялось.
остальные режимы работают ?

**Comment by Vladimir855** [comment]
> > > Привет, другие режимы пробовали? Там также?
> > > работает два режима  В44 и eth, запускаю с разных папок (разархив. и эту же папку скопировал), режим btc работает. Три дня подряд эфир вылетает, каждое утро заново запускаю, пробовал в разных вариациях и рандомы менял и sl 5 убирал. На эфире будет показывать баланс?
> 
> я проверю и отпишусь . эфир единственное что давно не обновлялось. остальные режимы работают ?

да

**Comment by Noname400** [comment]
ок. завтра все проверю. обнову выложу

**Comment by Vladimir855** [comment]
вчера днем запустил, сегодня опять стоит

**Comment by Vladimir855** [comment]
не запускается в этом режиме, пробовал по всякому 
![Screenshot_2021-12-21_08-26-12](https://user-images.githubusercontent.com/48643229/146876654-7ad9acda-4e77-41cb-8e1e-f94faf8bcaec.png)


Pulsar v4.5b не смог запустить, у тебя ссылки стоят которых нет

Как поменять язык в consts.py , со сменной языка как то не понятно, надо как то по проще

**Comment by Noname400** [comment]
вы не поставили pip install colorama

**Comment by Vladimir855** [comment]
> вы не поставили pip install colorama

поставил, на остальные вопросы будут ответы

**Comment by Noname400** [comment]
"Pulsar v4.5b не смог запустить, у тебя ссылки стоят которых нет" - можно поточнее...
"Как поменять язык в consts.py , со сменной языка как то не понятно, надо как то по проще" проще некуда 
mnemonic_lang:list = ['english','chinese_simplified']  добавляем языки в ковычках и через запятую. как пишутсся языки написано справа.
"Что за проект куда вставлять адреса и какие https://github.com/Noname400/Puzzle-1-BTC" - в описании есть ссылка почитайте

**Comment by Vladimir855** [comment]
"Pulsar v4.5b не смог запустить, у тебя ссылки стоят которых нет" - можно поточнее...
![Screenshot_52](https://user-images.githubusercontent.com/48643229/147052596-cbde46f0-a3af-4e86-b432-8ec0b435e2e5.png)

**Comment by Vladimir855** [comment]
https://github.com/bitaps-com/pybtc  будете как то реализовывать под себя?

**Comment by Vladimir855** [comment]
Заново качать zip папку

**Comment by Noname400** [comment]
> https://github.com/bitaps-com/pybtc будете как то реализовывать под себя?

Зачем? 

> "Pulsar v4.5b не смог запустить, у тебя ссылки стоят которых нет" - можно поточнее... ![Screenshot_52](https://user-images.githubusercontent.com/48643229/147052596-cbde46f0-a3af-4e86-b432-8ec0b435e2e5.png)

В моем р4позитори и такого нет

**Comment by Vladimir855** [comment]
Я скачивал от сюда https://gz.blockchair.com/ethereum/addresses/  там 0х в начале

**Comment by Noname400** [comment]
> С эфиром ошибка, после запуска работает не долго и останавливается
> 
> ![Screenshot_2021-12-18_14-42-44](https://user-images.githubusercontent.com/48643229/146639817-6041044b-1946-437f-b2b9-0abe2eb91ea3.png)

тут сложно сказать. у меня работал 2 дня все нормально

**Comment by Noname400** [comment]
> Я скачивал от сюда https://gz.blockchair.com/ethereum/addresses/ там 0х в начале

странно я качал 1 месяц назад 0x небыло

**Comment by Noname400** [comment]
> Заново качать zip папку

да. надо заменить все файлы

**Comment by Vladimir855** [comment]
у меня тоже запустилась но адреса переделал взял файл eth.txt c 0x кинул в блюм, закинул в прогу eth.bf и всё работает не тормозит

**Comment by Vladimir855** [comment]
К стати у фрутиса вот здесь Используйте Python: python eth_addresses_to_bin.py eth_addresses_in.txt eth_addresses_out.bin он говорит что после конверта 0х убирается
Вопрос - можно ли этот файл использовать для конверт в блюм в этой проге

**Comment by Vladimir855** [comment]
Ещё раз скачаю

**Comment by Vladimir855** [comment]
Заново скачал zip При смене языка ошибка

![Screenshot_2021-12-22_12-13-24](https://user-images.githubusercontent.com/48643229/147068576-fb0d0f63-8dd0-4112-8389-a1dbc1a2719f.png)

![Screenshot_2021-12-22_12-15-54](https://user-images.githubusercontent.com/48643229/147068666-7c62bb33-01b4-423b-b84b-8327f30046f8.png)

**Comment by Vladimir855** [comment]
в системной две папки мнемоник 
![Screenshot_2021-12-22_12-35-00](https://user-images.githubusercontent.com/48643229/147070893-1b103d4d-a402-4499-831f-825e4f764938.png)

**Comment by Noname400** [comment]
я переделал только-что файл создание блюм фильтра.
если он найдет 0х он удалит и создаст правильный. так что можете конвертировать им

**Comment by Noname400** [comment]
> К стати у фрутиса вот здесь Используйте Python: python eth_addresses_to_bin.py eth_addresses_in.txt eth_addresses_out.bin он говорит что после конверта 0х убирается Вопрос - можно ли этот файл использовать для конверт в блюм в этой проге

Нет

**Comment by Noname400** [comment]
https://drive.google.com/drive/folders/1E2rC7GSc59lAIJi_gD0O-tgGiXwcS7Wl?usp=sharing

**Comment by Vladimir855** [comment]
> https://drive.google.com/drive/folders/1E2rC7GSc59lAIJi_gD0O-tgGiXwcS7Wl?usp=sharing

Спасибо большое

**Comment by Vladimir855** [comment]
> Заново скачал zip При смене ошибка языка
> 
> ![Screenshot_2021-12-22_12-13-24](https://user-images.githubusercontent.com/48643229/147068576-fb0d0f63-8dd0-4112-8389-a1dbc1a2719f.png)
> 
> ![Screenshot_2021-12-22_12-15-54](https://user-images.githubusercontent.com/48643229/147068666-7c62bb33-01b4-423b-b84b-8327f30046f8.png)

Подскажи как с этим быть, что не так делаю

**Comment by Noname400** [comment]
скиньте свой батник

**Comment by Vladimir855** [comment]
у меня только ваши батники

**Comment by Vladimir855** [comment]
может удалить папку mnemonic а вашу оставить

**Comment by Noname400** [comment]
да

> может удалить папку mnemonic а вашу оставить

**Comment by Vladimir855** [comment]
ModuleNotFoundError: No module named 'mnemonic'

**Comment by Vladimir855** [comment]
вернул папку заработало но engl

**Comment by Noname400** [comment]
удалите pip3 uninstall mnemonic
и поставьте готовый из папки install (pip3 install mnemonic-0.20-py3-none-any.whl)

**Comment by Vladimir855** [comment]
Всё удалил заново скачал, всё установил поменял язык  
    version:str = '* Pulsar v4.8.4 multiT Hash160 *'
    mnemonic_lang:list = ['japanese'] # ['english', 'chinese_simplified', 'chinese_traditional', 'french', 'italian',
Ошибка
/Desktop/Hunt-to-Mnemonic-main# python3 -B PulsarMTv4.py -b BTC -db BF/5.bf -th 2 -m s -bit 128 -sl 5 -dbg 2 -bal
----------------------------------------------------------------------
Thank you very much: @iceland2k14 for his libraries!
----------------------------------------------------------------------
DEPENDENCY TESTING:
[I] TEST: OK! 
----------------------------------------------------------------------
[I] Version: * Pulsar v4.8.4 multiT Hash160 *
[I] Total kernel of CPU: 8
[I] Used kernel: 2
[I] Mode Search: BIP-BTC Standart
[I] Database Bloom Filter: BF/5.bf
[I] Languages at work: ['japanese']
[I] Work BIT: 128
[I] Description client: local
[I] Smooth start 5 sec
[I] Send mail: Off
[I] Check balance BTC: On
----------------------------------------------------------------------
Process 0:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "PulsarMTv4.py", line 55, in run
    mnemonic, seed_bytes = nnmnem(mem)
  File "/root/Desktop/Hunt-to-Mnemonic-main/funcP.py", line 398, in nnmnem
    print('Debug Mnemonic : '+ mnemonic)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 17-79: ordinal not in range(256)

Может здесь ошибка  PulsarMTv4.py
 55 mnemonic, seed_bytes = nnmnem(mem)

**Comment by Vladimir855** [comment]
В режиме btc мнемоник создаётся медленно но скорость ключей прыгает от 2000 до 4000 (2 ядра)
режим eth мнемоник по быстрей скорость от 1100 до 1700 (2 ядра)
эфир запустил позже битка по мнемонике перегнал биток

**Comment by Noname400** [comment]
> Всё удалил заново скачал, всё установил поменял язык
> 
> ```
> version:str = '* Pulsar v4.8.4 multiT Hash160 *'
> mnemonic_lang:list = ['japanese'] # ['english', 'chinese_simplified', 'chinese_traditional', 'french', 'italian',
> ```
> 
> Ошибка
> 
> ## /Desktop/Hunt-to-Mnemonic-main# python3 -B PulsarMTv4.py -b BTC -db BF/5.bf -th 2 -m s -bit 128 -sl 5 -dbg 2 -bal
> ## Thank you very much: @iceland2k14 for his libraries!
> ## DEPENDENCY TESTING:
> [I] TEST: OK!
> ## [I] Version: * Pulsar v4.8.4 multiT Hash160 *
> [I] Total kernel of CPU: 8
> [I] Used kernel: 2
> [I] Mode Search: BIP-BTC Standart
> [I] Database Bloom Filter: BF/5.bf
> [I] Languages at work: ['japanese']
> [I] Work BIT: 128
> [I] Description client: local
> [I] Smooth start 5 sec
> [I] Send mail: Off
> [I] Check balance BTC: On
> Process 0: Traceback (most recent call last): File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "PulsarMTv4.py", line 55, in run mnemonic, seed_bytes = nnmnem(mem) File "/root/Desktop/Hunt-to-Mnemonic-main/funcP.py", line 398, in nnmnem print('Debug Mnemonic : '+ mnemonic) UnicodeEncodeError: 'latin-1' codec can't encode characters in position 17-79: ordinal not in range(256)
> 
> Может здесь ошибка PulsarMTv4.py 55 mnemonic, seed_bytes = nnmnem(mem)

очень странно. у меня все нормально
![image](https://user-images.githubusercontent.com/74019756/147583297-884304e6-df9e-40fc-8b46-dac7b9bd2821.png)

**Comment by Noname400** [comment]
какая операционка ?

**Comment by Noname400** [comment]
> В режиме btc мнемоник создаётся медленно но скорость ключей прыгает от 2000 до 4000 (2 ядра) режим eth мнемоник по быстрей скорость от 1100 до 1700 (2 ядра) эфир запустил позже битка по мнемонике перегнал биток

сколько ядер на машине и сколько потоков ?

**Comment by Noname400** [comment]
мой слабенький VDS. показывает 2 ядра, но это не 2 ядра а 2 потока. и для того что бы программа не дралась за ресуосы я ставлю 1 ядро. надо понимать что если ставить больше чем есть физических ядер, программа ведет себя не предсказуемо

**Comment by Noname400** [comment]
![image](https://user-images.githubusercontent.com/74019756/147583765-82a25ff2-c267-4408-ad94-71051bd22b33.png)

**Comment by Vladimir855** [comment]
> > В режиме btc мнемоник создаётся медленно но скорость ключей прыгает от 2000 до 4000 (2 ядра) режим eth мнемоник по быстрей скорость от 1100 до 1700 (2 ядра) эфир запустил позже битка по мнемонике перегнал биток
> 
> сколько ядер на машине и сколько потоков?

на одной 8 использую 6 - 3 запуска по 2 ядра на другой 16 использую 12 - 3 запуска по 4 ядра

**Comment by Vladimir855** [comment]
у тебя опять исправления, заново скачивать zip

**Comment by Vladimir855** [comment]
помимо consts.py может ещё надо где то поменять язык

**Comment by Noname400** [comment]
Удали все файлы кроме фоюм фильтра.

**Comment by Noname400** [comment]
Скачай заново и запусти.

**Comment by Noname400** [comment]
> помимо consts.py может ещё надо где то поменять язык

Только там в конст

**Comment by Noname400** [comment]
2 ядра дают на бтц примерно 10000

**Comment by Vladimir855** [comment]
Привет, С праздничками! 
Вопрос - Возможно сохранить процесс? очень много перебрал, не хотелось заново начинать

**Comment by Noname400** [comment]
Так как все рандом, сохранять нет смысла. Я делал тест. Из 60млн было 12 повторений

**Comment by Vladimir855** [comment]
1 мне надо скрипт python2 переделать в python3 скажи этот конвертер нормальный?  https://360techexplorer.com/tools/python-2-to-3-converter/

2 как запустить скрипт который ты скидывал  https://github.com/Noname400/Hunt-to-Mnemonic/files/7833223/P.zip
в батнике python -B PulsarMTv4.py -b 44 -db btc.bf -cf custom.txt,  файл PulsarMTv4.py не нашел в папке, там main.py пробовал его подставить не запускает

**Comment by Vladimir855** [comment]
1 . уже свой есть - это какой, Hunt-to-Mnemonic? 
проверка онлайн бесполезная трата времени - почему? не согласен, по этому скрипту 2 адреса находил, пускай копейки, но находил. В других ПО как Hunt-to-Mnemonic  Rotor-Cuda  bsgs  keyhunt вообще ничего. Ещё 1 находил в этом скрипте https://github.com/7jdope8/Passphrases-from-file.

2 К стати недавно в  Hunt-to-Mnemonic нашло 5 адресов все по нулям, блюм базу брал из вашей ссылки   https://drive.google.com/drive/folders/1E2rC7GSc59lAIJi_gD0O-tgGiXwcS7Wl?usp=sharing

**Comment by Noname400** [comment]
1. еще не выкладывал. пока в разработке.
2. скрипт который вы выложили юзает словарь который вы ему подсовываете. (с превращениями) хант делает тоже самое (превращения не делает конечно)
3. почему трата времени... потому что медленно.

В итоге: всеми скриптами которыми вы пользовались и нашли они все работают со словарями. это разница с хантом
хотя хант тоже умеет это но он генерирует мнемоники из фраз или слов а эти прогу тупо конвертят как брайнфлайер
поэтому и сказал что у меня есть так как сейчас написал брайнфлайер на питоне с мультипотоком

насчет пустых адресов, да это возможно. но это база была собрана максимум адресов .... рекомендую проверить BTS SV и BTS CHASH

**Comment by Vladimir855** [comment]
1. Я хотел найти скрипт чтобы подставлять свои пароли по порядку и проверялось онлайн. Может тебе попадалась? Для меня на данный момент хорошие две  https://github.com/7jdope8/Passphrases-from-file   https://github.com/CryptoXploit/Bruteforce-Bitcoin-Brainwallet
2. В этом скрипте https://github.com/CryptoXploit/Bruteforce-Bitcoin-Brainwallet  как поменять иди заменить coinkit, хотелось запустить на 3 питоне. Может посмотришь если время будет.
3. Когда планируешь выпустить брайнфлайер на питоне с мультипотоком, хотелось попробовать?
4. рекомендую проверить BTS SV и BTS CHASH - Как проверить если прога кроме адреса и баланса ничего не выдала, даже не записала в found. Напечатала только в терминале и дальше продолжила работать.

**Comment by Noname400** [comment]
1. онлайн точно делать не буду.
2. сейчас со временем совсем никак. оплатили заказ. так что надо работать
3. не знаю, еще много хочется туда добавить
4. у тебя какая версия?

**Comment by Vladimir855** [comment]
у тебя какая версия? - 4.10.2 качал перед последним обновлением

**Comment by Noname400** [comment]
в версии 4,10,4 уже исправлено

**Comment by Vladimir855** [comment]
какие монеты по мимо бит эфир можно брутить

**Comment by Noname400** [comment]
"0","145","236","156","177","222","192","2","3","5","7","8","20","22","28","90","133","147","2301","175","216"

**Comment by Vladimir855** [comment]
охренеть это получается надо качать адреса разных монет, создать отдельный блюм, и выставить параметр python -B PulsarMTv4.py -b 44

**Comment by Noname400** [comment]
Все монеты можно сложить в 1 блюм.
вы удивитесь когда соберете его ...
к 1 хешу могут относится куча монет, при чем на 1 хеш может приходится до 3х монет с балансом

**Comment by Vladimir855** [comment]
> Все монеты можно положить в 1 блюм. вы удивитесь, когда соберете его ... к 1 хешу может относиться куча монет, при чем на 1 хеш может приходиться до 3х монет с балансом

все монеты положить, кроме бит и эфира - правильно?  параметр запуска для всех остальных монет -b 44?

**Comment by Noname400** [comment]
все кроме эфира.
и запускать на 44

**Comment by Vladimir855** [comment]
1. Выбор режима - Режим 's' - стандартный режим по спецификации BIP39
                                Режим 'e' - генерируется энтропия а из нее мнемоника.
В чём разница и какой лучший?
2. (-brain) - можно пример запуска, как прописывать? и ещё, как берутся слова из словарь.txt подряд или рандомно (если рандом то будут повторы)?
3. Код переведен полностью на систему логирования - это что значит?

**Comment by Noname400** [comment]
1. это сложно объяснить. они и разные и очень одинаковы. я перешел на энтропию.
2. пример есть в батнике, смотри репозиторий. слова для браина не берутся из словаря. это не брайнфлайер. они берутся их текста программы в частности мнемоника и сид(а также их перевернутые значения и убрания пробелов)
3. это значит что все записывается в файл через систему логирования а не через принудительной записи в файл.

**Comment by Vladimir855** [comment]
1. Если правильно понял для брайна берутся слова из мнемоник словаря - -english -chinese_simplified и т.д. 
2. Слова берутся по одному слову подряд?

**Comment by Noname400** [comment]
1. не слова а целиком фраза берется , и в разных комбинациях подается в браин. да языки подачи в браин зависят от выбраных языков для формирования мнемоники
3. нет для линукс не требуется до установка компонентов
4. сложно сказать. сколько памяти на VPS ?

**Comment by Vladimir855** [comment]
памяти на VPS много на 1- 16гб 2 - 32гб, при запуске память память много не потребляет примерно 50%

**Comment by Noname400** [comment]
2.паузы как таковой нет. Чтобы изменить ядра надо перезапустить
3. У меня работает. Всё отлично

**Comment by Vladimir855** [comment]
1. Можно поставить прогу на oracle linux? 
2. Не знаешь в чём отличия от Ubuntu?
3. Если поставлю граф. xfce на 1 ядро 1 озу программу потянет? (в программе указывая 1 ядро)

**Comment by Noname400** [comment]
1. не проверял
2. незнаю
3. оболочка будет забирать ресурсы. хотя и немного

**Comment by Vladimir855** [comment]
1. Привет, вижу перемудрил! Всё сложней стало, но это тебе видней. На ubuntu 20 трудно стало устанавливать  requests и bitcoinlib какие то не совместимости по версиям, вообщем папка BF-create вообще не работает не один скрипт.
2. Соединил все монеты в один файл кроме btc, eth запустил всё на -b44 посмотри правильно

![Screenshot_2022-01-28_23-40-38](https://user-images.githubusercontent.com/48643229/151619494-ecb5ab5d-8e68-4c87-b5fe-e3987a704135.png)

**Comment by Noname400** [comment]
да все верно запустил
ошибки скинь. их надо устронить

**Comment by Vladimir855** [comment]
Всё заработало, переустановил модули с pip3

**Comment by Noname400** [comment]
отлично. оказалось не так все сложно
