### ISSUE TITLE
сылки на блюмфильтры не работают

### ISSUE THREAD

**Issue by Knopius** [Noname400/Hunt-to-Mnemonic#24]
или на моем ресурсе:
https://drive.google.com/drive/folders/1oBMNxqwyYqp6Dx1q5j6erajf9wahGAda?usp=sharing (базы с адресами) https://drive.google.com/drive/folders/1ILhIERsWHTvQ1-HwgzQLyKm3G7VPzgjY?usp=sharing (готовые блюм фильтры)

**Comment by Noname400** [comment]
немогу зайти к вам и загрузить базы и блюмы

**Comment by Noname400** [comment]
проверьте ссылки

**Comment by Ak535Ak** [comment]
Да это твои же ссылки из README.md

**Comment by Noname400** [comment]
сори , я все удалил. нужно место.
вы можете выложить свои ссылки я закачаю на ваш гугл диск
