### ISSUE TITLE
Блюм

### ISSUE THREAD

**Issue by Ak535Ak** [Noname400/Hunt-to-Mnemonic#25]
Так как на windows не ставятся simplebloomfilter и bitarray то нет возможности создать БФ, есть ли возможность выложить готовый блюм на сторонний ресурс , приведенные ссылки в readme  не работают.

**Comment by Herowosboduna** [comment]
ссылки не работают!!!

**Comment by Noname400** [comment]
> Так как на windows не ставятся simplebloomfilter и bitarray то нет возможности создать БФ, есть ли возможность выложить готовый блюм на сторонний ресурс , приведенные ссылки в readme не работают.

Вам нужно поставить https://www.google.com/url?sa=t&source=web&rct=j&url=https://visualstudio.microsoft.com/downloads/%3Fq%3Dbuild%2Btools&ved=2ahUKEwjt2p3l0O30AhVGxosKHbi5DgUQFnoECAgQAQ&usg=AOvVaw1R4hByQgLMVXILHAA7iV3Y

**Comment by Noname400** [comment]
> Так как на windows не ставятся simplebloomfilter и bitarray то нет возможности создать БФ, есть ли возможность выложить готовый блюм на сторонний ресурс , приведенные ссылки в readme не работают.

загрузите и установите visual c++ build tools
https://visualstudio.microsoft.com/ru/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Comment by Noname400** [comment]
> ссылки не работают!!!

к сожалению мое пространство имеет ограничения.
выделите место и скиньте ссылку. я вам закачаю на гугл диск

**Comment by forevox** [comment]
а символ переноса строки нужно удалять?

**Comment by Noname400** [comment]
для стабильной работы только символ /n стандарт LINUX
в emeditor :
![image](https://user-images.githubusercontent.com/74019756/146819242-5774db91-63ad-45a0-8677-b63827b86cc9.png)
