### ISSUE TITLE
Не работает конвертация в hash160.

### ISSUE THREAD

**Issue by DJLazerjet** [Noname400/Hunt-to-Mnemonic#26]
Использовал базу биткоин-кошелей с blockchair для того чтобы их перевести в hash160, а затем в блюм. Так вот.. возникла проблема уже на стадии попытки конвертации адресов в hash160. После завершения выполнения скрипта addr_to_h160.py созданный файл, где должна храниться сконвертированная информация весит 0 байт (то бишь пустой). При этом все адреса, которые пыталась пропарсить прога - были скипнуты. Информация в файле blockchair выглядит как адрес кошелька, затем какое-то число, и так каждая строчка. Вот пример:

34xp4vRoCGJym3xR7yCVPFyCVPFHoCNxv4Twseo   26547968140649

Сам файл blockchair_bitcoin_addresses_latest.tsv на данный момент весит около 1.59GB.

И да.. есть ли у вас возможность залить куда-нибудь уже готовые файлы, а то ссылки на гугл-диск в readme.md не работают. Как вариант - использовать не только googledisk, а еще яндекс.диск и mega.nz.

**Comment by Noname400** [comment]
Расшарьте свой гуглдиск я закачаю готовые блюмы

**Comment by Noname400** [comment]
https://drive.google.com/drive/folders/1E2rC7GSc59lAIJi_gD0O-tgGiXwcS7Wl?usp=sharing

**Comment by DJLazerjet** [comment]
Скачал! Благодарю ^_^
