### ISSUE TITLE
ошибки при нахождении фразы

### ISSUE THREAD

**Issue by reseggy** [Noname400/Hunt-to-Mnemonic#28]
привет, тестировал со своими кошельками и при нахождении выдает следующее, что делать?
![image](https://user-images.githubusercontent.com/90745150/147415271-2c69a810-9b11-401c-91cb-99436dffea7f.png)

**Comment by Noname400** [comment]
проверю

**Comment by Noname400** [comment]
отключите проверку баланса . выдаст ошибку ?

**Comment by reseggy** [comment]
отключил, все работает правильно, переставил программу на последнюю версию и переставил питон, все работает и с проверкой баланса

**Comment by Noname400** [comment]
хорошо. если проблема устронена прошу закрыть обращение
