### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Ak535Ak** [Noname400/Hunt-to-Mnemonic#30]
![image](https://user-images.githubusercontent.com/79843719/147469347-93f88744-8dc7-490d-9ac2-983dea0c4a9d.png)
Win 10 с танцами и бубнами поставил все необходимые зависимости, в итоге ругается на bitarray насколько я понимаю, ставил не 1.9.2 а 2,3,4 так как на винду другого нет, возможно ли что причина в этом ? Есть ли какая то возможность запустить программу на винде без таких костылей ?

**Comment by Noname400** [comment]
На виду все ставится без костылей.
Сейчас вам надо поставить битаррай как в описании pip install bitarray==1.9.2

**Comment by Noname400** [comment]
ситуация исправилась ?
