### ISSUE TITLE
Eposta

### ISSUE THREAD

**Issue by dogukanqq** [Noname400/Hunt-to-Mnemonic#31]
When it finds balance, what can I do to save it in a text document instead of an e-mail?

**Comment by Noname400** [comment]
он сохранится автоматически

**Comment by dogukanqq** [comment]
which file does it save to, the software found a wallet

**Comment by dogukanqq** [comment]
> он сохранится автоматически

which file does it save to, the software found a wallet

**Comment by Noname400** [comment]
Found. Txt

**Comment by dogukanqq** [comment]
> Found. Txt

what was added in the last update

**Comment by Noname400** [comment]
это было всегда. если программа нашла что, она это записывает в файл found.txt
