### ISSUE TITLE
возможно сделать в -m custom -cw 1 что бы он шел по порядку словаря. от a до z

### ISSUE THREAD

**Issue by HackDOSS** [Noname400/Hunt-to-Mnemonic#32]

**Comment by Noname400** [comment]
Напишите мне в телегу

**Comment by Vladimir855** [comment]
> Напишите мне в телегу

Тоже интересно, ответь здесь

**Comment by Noname400** [comment]
Давно писал такой код. Он в один поток. Если надо скину

**Comment by Vladimir855** [comment]
скинь, а запуск его и модули те же

**Comment by Noname400** [comment]
[P.zip](https://github.com/Noname400/Hunt-to-Mnemonic/files/7833223/P.zip)
