### ISSUE TITLE
Проверка баланса

### ISSUE THREAD

**Issue by vkt987** [Noname400/Hunt-to-Mnemonic#33]
Уточните пожалуйста, при сгенерированной seed phrase мы имеем на ее основе master key, но основании которого в кошельке может быть сгенерировано несколько миллиардов Private Key. Каким образом происходит проверка баланса, выборка из первых?

**Comment by Noname400** [comment]
изначально проверяются 20 первых адресов:
но они вложены в аккаунты и а адреса отправки и сдачи:
выглядит так
Аккаунты (2)
    отправка сдача (2)
        адреса (20)

итого как вы видите происходить проверка 20 адресов в каждом аккаунте и в каждой линии отправки и сдачи
если не понятно пишите поясню подробнее

![image](https://user-images.githubusercontent.com/74019756/148671806-297c3442-3f7f-4681-a8d2-b3f218af4a6f.png)

**Comment by vkt987** [comment]
Понял, спасибо!
