### ISSUE TITLE
помоги)

### ISSUE THREAD

**Issue by GefGanty** [Noname400/Hunt-to-Mnemonic#34]
Привет!
Я относительно недавно начал изучать python (наверное где-то уже полтора года прошло), поэтому не прям много чего понимаю)
Вопрос, наверное тупой: что открывать?)

Если я открою батник run.bat, он открывает cmd с выполненной командой из батника, на которую возврат только 'Python', и дальше Pause и Press any key to continue.

Если открываю PulsarMTv4.py - появляется на секунду окно со скриншотов, затем появляется ошибка [E] File:  not found (логично, что между пробелами должно стоять имя файла, которое я должен был где-то указать, а где - я не понял).

В общем, подскажи пожалуйста, куда и какой файл мне надо положить и что открывать, буду очень благодарен, ибо я не понимаю что делать)) Спасибо!

**Comment by GefGanty** [comment]
Может я еще не то скачал что-то, на гитхабе первый раз что-то делаю lol
Я нажал на Code --> Download ZIP, распаковал архив и там уже возился

**Comment by Noname400** [comment]
прошу скиньте скрины. то что вы описываете не совсем понятно

**Comment by GefGanty** [comment]
Я просто прощу помочь с настройкой.
1. Не очень понятны пункты "Создаем HASH160 из Адресов" и "Создайте BloobFilter" Где взять для первого <in file>? <Out file> надо создать и указать путь или туда ничего писать не надо?
2. Я правильно понял, что редактировать аргументы надо в батнике? И запускать как программу тоже его надо? Или запускать надо файл PulsarMTv4.py?


P.S. у меня не грузится сайт https://gz.blockchair.com/ от слова совсем. Где можно взять файл с адресами, и его ли надо использовать в пункте "Создаём HASH160 из Адресов" как <in file>?

**Comment by Noname400** [comment]
https://gz.blockchair.com/ заработал
 адреса берете тут https://gz.blockchair.com/bitcoin/addresses/
редактируете его в emeditor
дальше все по описанию.

а лучше возбмите готовые бызы у меня на гугл диске
