### ISSUE TITLE
Вопросы по проге

### ISSUE THREAD

**Issue by Zelt-dev** [Noname400/Hunt-to-Mnemonic#35]
Крутой проект, надеюсь ты его не забросишь)) 
Так вот вопросы :
1) Находил уже какие-то кошельки с балансом?
2)Как вариант вместо отправки по почте сделать отправку через бота в тг

**Comment by Noname400** [comment]
Привет.
1. Я пока нет. За остальных говорить не буду
2. Думал уже об этом. Может позже.

**Comment by Smsu838** [comment]
Для телеги там все просто каждый может сам себе прикрутить если надо:

```
def send_telegram(text: str):
    token = "ВАШ:ТОКЕН"
    url = "https://api.telegram.org/bot" + token + "/sendMessage"
    channel_id = "-ИД КАНАЛА"
    r = requests.post(url, data={"chat_id": channel_id,"text": text})

    if r.status_code != 200:
        raise Exception("post_text error")
```

**Comment by Noname400** [comment]
> Для телеги там все просто каждый может сам себе прикрутить если надо:
> 
> ```
> def send_telegram(text: str):
>     token = "ВАШ:ТОКЕН"
>     url = "https://api.telegram.org/bot" + token + "/sendMessage"
>     channel_id = "-ИД КАНАЛА"
>     r = requests.post(url, data={"chat_id": channel_id,"text": text})
> 
>     if r.status_code != 200:
>         raise Exception("post_text error")
> ```

реализую в текущей редакции

**Comment by hamele0n26** [comment]
как настроить количество адресов для одной seed фразы? и какое стоит значение по умолчанию?

**Comment by Noname400** [comment]
файл funcP.py
например в режиме BTC:
по умолчанию стоит 1 аккаунт (349) (for nom2 in range(1):)
Входящие и исходящие: строка(350) for nom3 in range(2):
и 20 адресов каждом аккаунте * на входящее или исходящее (строка 351) for nom in range(20):

**Comment by hamele0n26** [comment]
а что значит входящие и исходящие?

**Comment by Noname400** [comment]
External / Internal

**Comment by hamele0n26** [comment]
дружище, подскажи, какая скорость выходит по seed'ам, т.е. я пытался изменить настройки таким образом, чтоб на один seed искал только один адрес m/44/0/0/0/0 но скорость он показывает высокую, а количество мнемоник которые перебрал маленкое, т.е. какое то не соответствие, или дай пример как настроить таким образом, может я не так что то делаю

**Comment by Noname400** [comment]
он паралельно ищет кучу всего.
если хотите оставить только генерацию сида и 1 адрес в нем напишите я выложу сюда файлы для вас
