### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by alex20087** [Noname400/Hunt-to-Mnemonic#37]
Приветствую Вас! При установке **pip install bitcoinlib** появляется ошибка:
![1](https://user-images.githubusercontent.com/98549401/151420364-f181af29-650b-4563-9c84-07dcb1efdd70.jpg)
Всё остальное устанавливается нормально. Инструменты сборки Microsoft установил. В чём проблема?

Python 3.10.2

**pip list:**

asn1crypto 1.4.0
base58     2.1.1
bip32utils 0.3.post4
bit        0.8.0
bitcoin    1.1.42
certifi    2020.6.20
cffi       1.15.0
chardet    3.0.4
coincurve  15.0.1
ecdsa      0.16.0
idna       2.10
mmh3       3.0.0
pip        21.3.1
pycparser  2.21
requests   2.24.0
setuptools 58.1.0
six        1.15.0
urllib3    1.25.10

Заранее благодарю за ответ...

**Comment by Noname400** [comment]
Добрый. эта библиотека нужна только для конвертации адресов.
остальное у вас получилось установить?

**Comment by alex20087** [comment]
Да, всё остальное встало прекрасно... Вот эта обильная "краснота" сильно смутила...

**Comment by alex20087** [comment]
Т.е. в этой библиотеке нет необходимости? Ваши BF с Гугл диска я скачал... Ничего запускать пока не пробовал... Просто я из "начинающих"... И больно всё это как-то не красиво...

**Comment by Noname400** [comment]
используйте мои блюмы.
программа должна работать уже

**Comment by alex20087** [comment]
Хорошо... Спасибо... Чуть позже попробую всё запустить... И, всё же, интересно, почему ошибка?

**Comment by g00dwin555** [comment]
pip3 при инстале используйте

**Comment by alex20087** [comment]
Спасибо...

**Comment by alex20087** [comment]
pip3 - то же самое... та же ошибка...

**Comment by Noname400** [comment]
sudo apt-get install python3-dev libgmp3-dev
sudo pip3 install fastecdsa
sudo pip3 install bitcoinlib

**Comment by alex20087** [comment]
sudo - это разве не linux? Я не совсем "профи"... Не получается... Ладно... Спасибо, что постарались помочь... Пока оставим эту тему...
