### ISSUE TITLE
BF

### ISSUE THREAD

**Issue by Delti42** [Noname400/Hunt-to-Mnemonic#4]
Здравствуйте! Как вы загружаете все файла блюмфильтра для поиска?

**Comment by Noname400** [comment]
извините немного не понял вопрос.
для каждой поиска свой фильтр
для BIP32 - 32.bf / для BIP44 - 44.bf / для BIP49 - 49.bf

**Comment by Delti42** [comment]
> извините немного не понял вопрос.
> для каждой поиска свой фильтр
> для BIP32 - 32.bf / для BIP44 - 44.bf / для BIP49 - 49.bf
У вас на гуглдрайв много файлов bf как их загружать для поиска?

**Comment by Delti42** [comment]
И чем отличаются эти файлы для BIP32 - 32.bf / для BIP44 - 44.bf / для BIP49 - 49.bf ?

**Comment by Noname400** [comment]
это разные адреса... почитайте матчасть пожалуйста

**Comment by Noname400** [comment]
32 это адреса на 1
44 это другой путь адреса на 1
49 другой путь адреса на 3
84 другой путь адреса на bc1

**Comment by Delti42** [comment]
Подскажите 12mvvF8dyTurBu1HUyZmbJhsczBqpUnA5E | 19hG7FdeNcBWox7E7uYTtxCDM7EQcuQ9Mh | 5f5e418f86cdf090efe2c54ed6be562e281a5381 | 16NhBnW2NXCbQXn9g9Aqeas5dUjfXWhyMH | 13776fc386dc48f2059cbdb853167afe387cff97 | 1N5ANJNHud3j6TswTCtU8hbaiA5vvK8W78 | TRUE | 量 朝 薯 烃 完 张 聚 固 症 彩 循 命 | KxiS8izpCAm4FKvzLqiVnUrBupi6NtexyCPU7boSTRyPyknnUngQ | BIP 44 / BITCOIN_CASH. это видимо ложные срабатывания?

**Comment by Delti42** [comment]
и хотелось бы узнать почему на один приватный ключ выдает 4 адреса

**Comment by Noname400** [comment]
> Подскажите 12mvvF8dyTurBu1HUyZmbJhsczBqpUnA5E | 19hG7FdeNcBWox7E7uYTtxCDM7EQcuQ9Mh | 5f5e418f86cdf090efe2c54ed6be562e281a5381 | 16NhBnW2NXCbQXn9g9Aqeas5dUjfXWhyMH | 13776fc386dc48f2059cbdb853167afe387cff97 | 1N5ANJNHud3j6TswTCtU8hbaiA5vvK8W78 | TRUE | 量 朝 薯 烃 完 张 聚 固 症 彩 循 命 | KxiS8izpCAm4FKvzLqiVnUrBupi6NtexyCPU7boSTRyPyknnUngQ | BIP 44 / BITCOIN_CASH. это видимо ложные срабатывания?

Да это ложноположительное срабатывание (это бывает)

**Comment by Noname400** [comment]
> и хотелось бы узнать почему на один приватный ключ выдает 4 адреса

я хотел охватить возможный не не возможный диапазон ключей
стандартный ключ для BIP44 - 44/0/0/0/0 это сжатый ключ
но я из одной мнемонике на BIP44 получаю ключи из пути 44/0/0/0 и 44/0/0/0/0 
ключи и сжатые и не сжатые, раньше  использовали не сжатые ключи сейчас все сжатые
ктому-же ведется поиск и по ключам из пазлов.

**Comment by evgenyunholy** [comment]
Приветствую. Где можно найти инфу по Блуму, использованном в скрипте? Хочу себе прикрутить. 
При создании BF файла какими данными он забивается? Считывается, как я понял в двоичке

**Comment by Noname400** [comment]
> Приветствую. Где можно найти инфу по Блуму, использованном в скрипте? Хочу себе прикрутить.
> При создании BF файла какими данными он забивается? Считывается, как я понял в двоичке

привет.
https://github.com/dnanhkhoa/simple-bloom-filter
данные любые.
на выходе обычный бинарник

**Comment by evgenyunholy** [comment]
Благодарю. А ты еще обмолвился на счет создания баз для блума. Это Ноду нужно ставить? Чтобы тот же трон выкачать, который bip44, содержащийся в коде, поддерживает. 
И будет ли дорабатываться эта версия программы или на Раст перейдешь? Хотел исходники свои скинуть. Достиг скорости 10к валидных мнемоников на одном ядре

**Comment by Noname400** [comment]
Без фул нобы никак. Я выкачиваю потом парю. Примерно по 2, 3 ноды за неделю.
На руст не буду. Перепишу код с вставками длл. Длл на С написана. Будет увеличение скорости.
Проект будет рости. Однозначно.
Если есть улучшения, давай добавил.

**Comment by evgenyunholy** [comment]
Завтра скину наработки, куски кодов. 
Попробую ноду трона поставить. Хочу через api чекать на баланс сразу.

**Comment by Noname400** [comment]
лучше напрямую через RPC. так будет быстрее

**Comment by Noname400** [comment]
какой библиотекой пользуетесь ? за счет чего добились скорости ?
у меня сейчас +-16 валют уже
база почти 3 гига.
и есть чужая база на 32 гига. но ее надо держать в пямяти , а у меня столько нет.
в блюме надо ставить fp_prob=1e-12, иначе будет много срабатываний.
я сейчас хочу объеденить bip32,33,49 + eth за один прогон. думаю будет интересно.
итого база будет в размере 4гб

**Comment by evgenyunholy** [comment]
https://github.com/evgenyunholy/bip39tgen
Вот форк исходника сделал. В питоне пару недель всего, поэтому не могу сказать что там используется. Вроде hashlib и сжатая кодировка. 
Хочу собрать отдельные оффлайн скрипты для каждой валюты. Чтоб скорость не резалась и пути деривации считались только первые. 
Для какого нибудь Трона это будет идеально

**Comment by evgenyunholy** [comment]
> это всего лишь сжатая реализация списка слов 2048 и неизвестно на каком языке.
> ктомуже в коде не соблюдаются правила спецификации BIP39

Язык английский. 
Каждый мнемоник генерируется правильно. 
Проверял.

**Comment by Noname400** [comment]
проверял на сколько она быстрее https://github.com/trezor/python-mnemonic
ктомуже это не самое главное.
самая большая потеря идет в EC и SEC256K1

**Comment by evgenyunholy** [comment]
Трезоровский медленнее. 
На моем 10к в секунду на ryzen 5, а мнемоник трезоровский чуть больше 100. 
Главное начать. Сначала скоростные мнемы, потом либы и тд) 
Hashlib, пишут, от cpython или cython надо использовать. Это си и питон вместе. Будет еще больше скорость. 
Pyopencl мозгов не хватило поставить, а может на Ryzen он и не ставится

**Comment by Noname400** [comment]
> Pyopencl мозгов не хватило поставить, а может на Ryzen он и не ставится
это уже после откатки алгоритма
> На моем 10к в секунду на ryzen 5, а мнемоник трезоровский чуть больше 100.
проверю сегодня
> Главное начать. Сначала скоростные мнемы, потом либы и тд)
отдельно не получится. тут все одно от другого (там секунда там 5 там половина

**Comment by evgenyunholy** [comment]
В общем нашел инфу по трону. Нода не нужна для извлечения базы адресов. есть готовые снапы, некоторые делают каждый день. https://developers.tron.network/docs/mainnet-backups

**Comment by evgenyunholy** [comment]
Noname400, нашел еще у товарища SECP256K1 Dll, склееные с питоном. глянь, может чего вытянешь. У него в репозиториях много интересного еще есть https://github.com/iceland2k14/bsgs

**Comment by Noname400** [comment]
> В общем нашел инфу по трону. Нода не нужна для извлечения базы адресов. есть готовые снапы, некоторые делают каждый день. https://developers.tron.network/docs/mainnet-backups. к сожалению, с моим 4g интернетом я не осилю скачать

Я скачаю гляну вечером.

**Comment by stanilab** [comment]
Доброго дня. Перефразирую первый вопрос по BF. Где можно скачать файлы фильтра? По указанной ссылке на гугл упираемся в ошибку. Я собирал  все базы сам, но червяк сомнения все таки имеется, спасибо

**Comment by Noname400** [comment]
могу создать для вас . 
сомнений не может быть
все просто
сначало h160
потом Сbloom
в фильтр попадают только правильные адреса
