### ISSUE TITLE
error

### ISSUE THREAD

**Issue by astral2009** [Noname400/Hunt-to-Mnemonic#6]
Desktop/Hunt-to-Mnemonic-main$ python h160.py in file h160.txt out file btc.txt
  File "h160.py", line 19
    print("Total line ->" + str(line_10), end='\r')
                                             ^
SyntaxError: invalid syntax

**Comment by Noname400** [comment]
какая версия питона у вас ?

**Comment by astral2009** [comment]
a$ python -V
Python 2.7.18
a$ python3 -V
Python 3.8.10

a:~/Desktop/Hunt-to-Mnemonic-main$ python h160.py in file base58.txt out file btc.txt
  File "h160.py", line 19
    print("Total line ->" + str(line_10), end='\r')
                                                                ^
SyntaxError: invalid syntax
a~/Desktop/Hunt-to-Mnemonic-main$ python3 h160.py in file base58.txt out file btc.txt
Ошибка. Слишком много параметров.
a~/Desktop/Hunt-to-Mnemonic-main$

**Comment by Noname400** [comment]
python3 h160.py base58.txt btc.txt

**Comment by astral2009** [comment]
спасибо помогло

**Comment by astral2009** [comment]
вылезла еще одна ошибка
python3 Cbloom.py hash160 32.bf
all lines -> 24962397
========== Bloom Filter START==========
===========File input -> hash160
===========File output -> 32.bf
========== ADD Bloom Filter ==========
========== Bloom Filter Statistic ==========
+ Capacity: 24962397 item(s)
+ Number of inserted items: 24962397
+ Filter size: 1076697147 bit(s)
+ False Positive probability: 1e-09
+ Number of hash functions: 30
+ Input file: hash160
+ Output file: 32.bf

========== Bloom Filter Start Save File ==========
========== Bloom Filter END Save File ==========
python3 mainMT2-hash.py -b32 -d BF -t 10 -mr -w 12
------------------------------------------------------------
* Version:  Pulsar v3.6.2 multiT Hash160 
* Total kernel of CPU: 88 
* Used kernel: 10 
* Mode Search: BIP-32 Random 
* Dir database Bloom Filter: BF 
* Languages at work: ['english'] 
---------------Load BF---------------

File: 32.bf not found.

**Comment by Noname400** [comment]
В какой папке лежит Файл 32.bf

**Comment by astral2009** [comment]
все лежит в одной папке и 32 и 44

**Comment by Noname400** [comment]
python3 mainMT2-hash.py -b 32  -t 10 -m r -w 12
надо убрать -d раз у вас база лежит там же где и программа

**Comment by astral2009** [comment]
python3 mainMT2-hash.py -b 32 -t 10 -mr -w 12
------------------------------------------------------------
* Version:  Pulsar v3.6.2 multiT Hash160 
* Total kernel of CPU: 88 
* Used kernel: 10 
* Mode Search: BIP-32 Random 
* Dir database Bloom Filter: BF 
* Languages at work: ['english'] 
---------------Load BF---------------

File: 32.bf not found.

**Comment by Noname400** [comment]
Что бы долго не разбираться, создай те папку bf и перенесите туда базы

**Comment by Noname400** [comment]
Я завтра разберусь в чем дело.

**Comment by astral2009** [comment]
python3 mainMT2-hash.py -b 32 -t 10 -mr -w 12
------------------------------------------------------------
* Version:  Pulsar v3.6.2 multiT Hash160 
* Total kernel of CPU: 88 
* Used kernel: 10 
* Mode Search: BIP-32 Random 
* Dir database Bloom Filter: BF 
* Languages at work: ['english'] 
---------------Load BF---------------
Bloom Filter 32.bf Loaded

File: btc30.h160 not found.
перенес в папку и загрузилось но теперь это требует))

**Comment by astral2009** [comment]
вроде получилось но прогресса не видно
python3 mainMT2-hash.py -b 32 -t 10 -mr -w 12
------------------------------------------------------------
* Version:  Pulsar v3.6.2 multiT Hash160 
* Total kernel of CPU: 88 
* Used kernel: 10 
* Mode Search: BIP-32 Random 
* Dir database Bloom Filter: BF 
* Languages at work: ['english'] 
---------------Load BF---------------
Bloom Filter 32.bf Loaded
File address pazzle BTC~30 Loaded.
-------------------------------------

**Comment by astral2009** [comment]
[*] Cycle: 2 | Total keys 8000 | Speed 2 key/s | Found 0 

чо то не то со скоростью

**Comment by Noname400** [comment]
какой у вас LINUX ?
запустите с одним ядром и с генерацией по стандарту
python3 mainmt2-hash.py -b 32 -t 1 -m s
потом запустите в режиме отладки ненадолго
python3 mainmt2-hash.py -b 32 -t 1 -m s -e 2

**Comment by astral2009** [comment]
5.8.0-53-generic #60~20.04.1-Ubuntu
в режиме отладки в первые секунды нормальная скорость а потом тупо тормозит,при чем весь комп.хотя он очень мощный

**Comment by Noname400** [comment]
Я выложу сегодня бету новой версии

**Comment by Noname400** [comment]
Попробуйте. bat файл приложил

**Comment by astral2009** [comment]
python3 PulsarMT2-hash.py -b 44 -t 2 -m s -c home -w 12 -s no -em no
-----------------------------------------------------------
* Version:  Pulsar v3.7.6b multiT Hash160 
* Identificator system: b'00000000-0000-0000-0000-cf6c82db9375'
* Total kernel of CPU: 88 
* Used kernel: 2 
* Mode Search: BIP-44 Standart 
* Dir database Bloom Filter: BF 
* Languages at work: ['english'] 
* Description Server: home 
* Mode debug: Off
* Send mail: Off
* Send Statistic to server: Off
* Bloom Filter 44.bf Loaded.
* Bloom Filter 44.bf Loaded.
* File address pazzle BTC~30 Loaded.
* File address pazzle BTC~30 Loaded.

минут 10 на месте стоит и все

**Comment by astral2009** [comment]
ставлю 20 ядер из 44 и у меня комп тупо виснет,что то ты намудрил там с софтом.

**Comment by astral2009** [comment]
и нафига тут системы эти идентификации сервер емейлы и т.д?больше похоже что будет в вирус переделан.

**Comment by Noname400** [comment]
> и нафига тут системы эти идентификации сервер емейлы и т.д?больше похоже что будет в вирус переделан.

идентификатор системы нужен для веб мониторинга клиентов.
у меня 6 серверов крутится и мне надо знать кто что нашол и кто в работе а кто мог отвалится
Send mail: Off
Send Statistic to server: Off
у тебя все отключено

сделай sudo pip3 list

**Comment by Noname400** [comment]
никакого вируса. вы видите код.
![image](https://user-images.githubusercontent.com/74019756/126379708-12b3b192-f4aa-4a45-bcaf-07720cdf9b6c.png)
![image](https://user-images.githubusercontent.com/74019756/126379734-bce01a9d-9856-47c0-8cc7-eb7fbe740534.png)
![image](https://user-images.githubusercontent.com/74019756/126379744-8f3d9fdb-1ded-47c7-bfda-1086bc68035a.png)
и т.д.

**Comment by astral2009** [comment]
![Screenshot from 2021-07-20 21-51-50](https://user-images.githubusercontent.com/87622780/126380162-869a2c95-5ad8-4b73-a8cb-3f92c9184207.png)
apt-clone              0.2.1               
apturl                 0.5.2               
astroid                2.3.3               
bip-utils              1.11.1              
bitarray               1.9.2               
blinker                1.4                 
Brlapi                 0.7.0               
certifi                2019.11.28          
chardet                3.0.4               
Click                  7.0                 
cmudict                0.4.5               
colorama               0.4.3               
command-not-found      0.3                 
configobj              5.0.6               
cryptography           2.8                 
cupshelpers            1.0                 
dbus-python            1.2.16              
defer                  1.0.6               
distro                 1.4.0               
distro-info            0.23ubuntu1         
ecdsa                  0.17.0              
entrypoints            0.3                 
httplib2               0.14.0              
idna                   2.8                 
isort                  4.3.4               
joblib                 1.0.1               
keyring                18.0.1              
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
lazy-object-proxy      1.4.3               
logilab-common         1.4.3               
louis                  3.12.0              
macaroonbakery         1.3.1               
Mako                   1.1.0               
MarkupSafe             1.1.0               
mccabe                 0.6.1               
mmh3                   3.0.0               
mnemonic               0.19                
netifaces              0.10.4              
nltk                   3.6.2               
oauthlib               3.1.0               
olefile                0.46                
PAM                    0.4.2               
pexpect                4.6.0               
Pillow                 7.0.0               
pip                    20.0.2              
pronouncing            0.2.0               
protobuf               3.6.1               
psutil                 5.5.1               
pycairo                1.16.2              
pycups                 1.9.73              
PyGObject              3.36.0              
PyICU                  2.4.2               
PyJWT                  1.7.1               
pylint                 2.4.4               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyRFC3339              1.1                 
pysha3                 1.0.2               
python-apt             2.0.0+ubuntu0.20.4.5
python-dateutil        2.7.3               
python-debian          0.1.36ubuntu1       
pytz                   2019.3              
pyxdg                  0.26                
PyYAML                 5.3.1               
regex                  2021.7.6            
reportlab              3.5.34              
requests               2.22.0              
requests-unixsocket    0.2.0               
SecretStorage          2.3.1               
setuptools             45.2.0              
simplebloomfilter      1.0.0               
simplejson             3.16.0              
six                    1.14.0              
systemd-python         234                 
tqdm                   4.61.2              
ubuntu-advantage-tools 27.0                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unattended-upgrades    0.1                 
urllib3                1.25.8              
usb-creator            0.3.7               
wadllib                1.3.3               
wheel                  0.34.2              
wrapt                  1.11.2              
xkit                   0.0.0

**Comment by Noname400** [comment]
Если запускаете с 1 потоком скорость тоже низкая ?
у вас случайно не AWS Elastic ?

**Comment by astral2009** [comment]
да
![Screenshot from 2021-07-21 05-13-11](https://user-images.githubusercontent.com/87622780/126419767-f3a04dc1-a1e7-43ad-af75-a7b5193f8634.png)

**Comment by Noname400** [comment]
запустите 5 потоков и дайте команду топ а консоле

**Comment by Noname400** [comment]
и кстате с таким железом вам выгоднее использовать keyhunt

**Comment by Noname400** [comment]
режим BSGS
по ваше проблеме мне самому интересно. так что разберусь

**Comment by Noname400** [comment]
Вы знакомы с изолированной средой для Python ?

**Comment by astral2009** [comment]
можно ваш телеграмм,а то тут сильно долго

**Comment by Noname400** [comment]
@hunt_mnemonic

**Comment by Noname400** [comment]
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
sudo apt install -y python3-venv
mkdir hunt && cd hunt
python3 -m venv env
source env/bin/activate

https://netpoint-dc.com/blog/python-venv-ubuntu-1804/

**Comment by OceanGW** [comment]
> Desktop/Hunt-to-Mnemonic-main$ python h160.py in file h160.txt out file btc.txt
> File "h160.py", line 19
> print("Total line ->" + str(line_10), end='\r')
> ^
> SyntaxError: invalid syntax

me,too.
When  I tried:  python3.7 ./BF-create/h160.py /mnt/f/wallet_db/dash_base58.txt  ./BF/dash.bf
all lines -> 1418310
===========File input -> /mnt/f/wallet_db/dash_base58.txt
===========File output -> ./BF/dash.bf
Traceback (most recent call last):
  File "./BF-create/h160.py", line 46, in <module>
    convert(file_in,file_out,line_count)
  File "./BF-create/h160.py", line 23, in convert
    adr160 = base58.b58decode_check(adr58).hex()[2:]
  File "/home/tonylinux/.local/lib/python3.7/site-packages/base58/__init__.py", line 152, in b58decode_check
    result = b58decode(v, alphabet=alphabet, autofix=autofix)
  File "/home/tonylinux/.local/lib/python3.7/site-packages/base58/__init__.py", line 124, in b58decode
    acc = b58decode_int(v, alphabet=alphabet, autofix=autofix)
  File "/home/tonylinux/.local/lib/python3.7/site-packages/base58/__init__.py", line 106, in b58decode_int
    ) from None
ValueError: Invalid character <->
any idea?

**Comment by Noname400** [comment]
I check. Need 10 min

**Comment by Noname400** [comment]
https://github.com/Noname400/Hunt-to-Mnemonic/tree/main/BF-create
я обновил h160.py
теперь он игнорирует плохие ключи. Если такие ключи есть, проверьте свой список адресов

**Comment by OceanGW** [comment]
> https://github.com/Noname400/Hunt-to-Mnemonic/tree/main/BF-create
> я обновил h160.py
> теперь он игнорирует плохие ключи. Если такие ключи есть, проверьте свой список адресов

python3 ./BF-create/h160.py /mnt/f/wallet_db/dash_base58.txt ./BF/dash.bf
all lines -> 1418310
===========File input -> /mnt/f/wallet_db/dash_base58.txt
===========File output -> ./BF/dash.bf
Error - 1115 | Total line -> 1400000
 Finish
Finish
working like a charm! good work! thank u !

**Comment by Noname400** [comment]
базы есть тут https://drive.google.com/drive/folders/1oBMNxqwyYqp6Dx1q5j6erajf9wahGAda?usp=sharing
