### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PDOGEDEV** [Noname400/Hunt-to-Mnemonic#7]
Thanks, looks interesting.
I have created all bloom filters but when I run only the btc filters are running according to terminal.

Its not loading all of the filters, how do I solve that?
I am using -m s

**Comment by PDOGEDEV** [comment]
I noticed a similar question was asked before.

Does the bip44 filter load all the alt coins filter too? just that they wont load in terminal?

**Comment by PDOGEDEV** [comment]
Sorry for spamming lol,

but yeah, mine wont load these

Version:  Pulsar v3.3.0 multiT  
* Total kernel of CPU: 6  
* Used kernel: 2  
* Mode Search: BIP-44 Энтропия  
* Dir database Bloom Filter: BF  
---------------Load BF---------------  
Bloom Filter ltc.bf Loaded  
Bloom Filter dash.bf Loaded  
Bloom Filter eth.bf Loaded  
Bloom Filter doge.bf Loaded  
Bloom Filter cash.bf Loaded  
Bloom Filter sv.bf Loaded  
Bloom Filter btc.bf Loaded  
-------------All BF loaded-----------  
[*] cycle: 1 | total key: 1260 | key/s: 880 in process cpu0 | Found 0  
[*] cycle: 2 | total key: 2520 | key/s: 909 in process cpu0 | Found 0  
[*] cycle: 1 | total key: 1260 | key/

How do I load all BF?

**Comment by PDOGEDEV** [comment]
![image](https://user-images.githubusercontent.com/84231696/126899716-f0fb72b5-c105-49b0-9ea2-6243bbf29898.png)

**Comment by PDOGEDEV** [comment]
Looks like I need the entropy mode but I can not find that command

**Comment by Noname400** [comment]
я постараюсь Вам сегодня расширено ответить,

**Comment by PDOGEDEV** [comment]
> я постараюсь Вам сегодня расширено ответить,

Thank you, will you upload to google?
Is it correct that it is all the other .hex files I need?

**Comment by Noname400** [comment]
1. Режим энтропии -m r
2. 44.BF - в этот файл собраны уникальные hash160 всех альткоинов которые я смог достать (BITCOIN, BITCOIN_CASH, LITECOIN, DASH, DOGECOIN, BITCOIN_SV). в версии 3.8  я добавлю ZCASH
3. в фильтре ETH.BF собраны 90 000 000 адресов, поэтому он больше (Скоро я соберу новый фильтр)
4. Edit3 -  я не совсем вас понял. создать hash160 из адресов можно с помощью Hunt-to-Mnemonic/BF-create/h160.py
5. после этого нужно из файла hash160 собрать файл BF . Hunt-to-Mnemonic/BF-create/Cbloom.py
6. я загружаю все обновления готовых баз на гугл диск.
7. если у вас есть свой список адресов сделайте как я написал выше. или можете мне его скинуть, я вам помогу создать ваш фильтр

Если есть еще вопросы задавайте.
проект растет постоянно, нужны свежие идеи )))
в планах перейти на RUST, он более быстрый. но пока еще много чего хочу сделать включая сервер статистики и проверки найденных адресов на баланс

**Comment by PDOGEDEV** [comment]
oh ok, so its not only running bitcoin now but also the other ones? meaning that eth needs to run separately?

**Comment by Noname400** [comment]
1. в BIP44 ((BITCOIN, BITCOIN_CASH, LITECOIN, DASH, DOGECOIN, BITCOIN_SV). в версии 3.8 я добавлю ZCASH)
2. -b ETH - поиск по ETH и ETC (да режим поиска ETH и ETC запускается отдельно)
![image](https://user-images.githubusercontent.com/74019756/126905795-4248953b-8df7-4683-8ec6-258198c88f57.png)
3. в файле btc30.h160 находятся hash160 из головоломки BTC. программа ищет все возможные пути для сокровищ и параллельно   для головоломки
4. пока были только ложные срабатывания. но у меня мало мощностей.
5. -s - создание согласно стандарта BIP39 включая языки указанные в стандарте english, chinese_simplified, chinese_traditional, french, italian, spanish, czech, korean, japanese, языки вы можете выбирать сами.
6. -r - полная случайность . в этой случайности могут быть разные мнемоники и разные языки. она не соответствует BIP39 и я вляпается чистым экспериментом.

**Comment by PDOGEDEV** [comment]
Thank you, I guess -s is the way to go

**Comment by PDOGEDEV** [comment]
Would it be possible to use your own bip wordlist?
For example if I would like to use the english wordlist but much reduced with fewer words?

**Comment by Noname400** [comment]
я могу сделать это для вас

**Comment by PDOGEDEV** [comment]
> я могу сделать это для вас

Thanks for great support, you are very friendly.
Are you certain all the formulas are correct? did you verify with the coleman site?

Also, brainflayer works like 50-100 times faster, I guess it is the formulas and correct encryption that takes time?

**Comment by Noname400** [comment]
Отвечу завтра. уже ночь

**Comment by PDOGEDEV** [comment]
> Отвечу завтра. уже ночь

Thanks, I see you have forked bip39generator, the same guy also has a project called bip39pro that creates valid phrasea for brainflayer, what is the advantages of your program since its much slower?

Is it because of the checking of alt coins? or is it something else?

**Comment by Noname400** [comment]
> > Отвечу завтра. уже ночь
> 
> Спасибо, я вижу, вы разделили bip39generator, у того же парня также есть проект под названием bip39pro, который создает правильные фразы для увлеченных мозгами, каковы преимущества вашей программы, поскольку она намного медленнее?
> 
> Это из-за проверки альт-монет? Или что-то еще?

нет. разделил для памятки. но потом понял, что зря это сделал так как код крайне не корректный.

**Comment by Noname400** [comment]
> > я могу сделать это для вас
> 
> Спасибо за отличную поддержку, вы очень дружелюбны.
> Вы уверены, что все формулы верны? вы проверяли с сайтом coleman?
> 
> Кроме того, brainflayer работает примерно в 50-100 раз быстрее, я думаю, это формулы и правильное шифрование требуют времени?
> 
> Brainflayer предназначен для мозговых кошельков, что означает, что он не совместим с BIP39, поэтому, скорее всего, он не будет работать должным образом.
> 
> Здесь все семена действительны и также проверены на нескольких путях деривации?
> 
> Или только BIP32 проверяет разные пути? это не нужно для BIP44?
> 
> по организации BIP-32 база данных '32.bf'
> сейчас проверяет следующие пути:
> m/0/0
> m/0/0'
> m/0'/0
> m/0'/0'
> m/0'/0/0
> m/0'/0/0'
> m/0'/0'/0
> m/0'/0'/0'
> m/44'/0'/0'/0
> m/44'/0'/0'/0'
> 
> по организации BIP-44 база данных '44.bf'
> по организации BIP-49 база данных '49.bf'
> по организации BIP-49 база данных 'eth.bf'
> 
> Или проверяет несколько путей? и поэтому он четыре раза загружает фильтры?
> ![изображение](https://user-images.githubusercontent.com/84231696/126908789-88b58afa-1450-4be7-b8e6-1ac17b732152.png)
> 
> А что это значит? мне нужно это исправить или все в порядке?
> ![изображение](https://user-images.githubusercontent.com/84231696/126908767-60b17a98-3c0a-4ea4-abb7-f03245aedbfe.png)

1. все результаты по коду проверяю тут (обязательно)
https://iancoleman.io/bip39/
https://www.indicrypto.com/bitcointools/
2. Брайнфлайер работает по другому. он не умеет работать с мнемониками. Он работает быстрее потому что написан на C++. я к сожалению не пишу на C++, поэтому буду потом переносить программу на RUST/
3. при ключе -s все семена правильные. проверка ведется по правильным и всем возможным путям деревации. в версии 3,8 будет добавлено проверка аккаунтов в пути. (m/0/1/0/i, m/44/0/0/i)
4. только в BIP32 есть разные пути деревации
5. в BIP44 есть аккаунты , а также EXT и INT кошельки (версия 3,8 будет реализовано)
6. да 32.BF это только BIP32
7. HARDHED пути в 3,8 я уберу, вариантов что кто то их будет использовать или использовал когда-то мало вероятны. (m/0'/0'/0')
8. да BIP32 - 32.bf, BIP44- 44.bf, ETH+ETC - eth.bf
9. BIP49 был удален, так как мы ищем потерянные сокровища а не чужие деньги.
10. программа загружает фильтр отдельно в каждый поток. когда вы создаете 4 процесса значит фильтр загрузится 4 раза, и съест в 4 раза больше памяти. (в версии 4 будем от этого уходить на локальный клиент-сервер)
11. > А что это значит? мне нужно это исправить или все в порядке?
> ![изображение](https://user-images.githubusercontent.com/84231696/126908767-60b17a98-3c0a-4ea4-abb7-f03245aedbfe.png)
Это нормально. я добавил функцию для мониторинга на сервере как работают разные воркеры. 
вы можете отключить отправку статистики на сервер <-s no>
12. для проверки данных. можно использовать функцию отладки -e1 или -e2 и сверить их с данными https://iancoleman.io/bip39/
13. также можете отключить отправку почты <-em no>

**Comment by PDOGEDEV** [comment]
Thanks, would it not be possible to just run your code and send to brainflayer to make it faster?

Will rust be very much faster?

Can you help me to add bip49 to the main program? I am doing it for research and not for looking for others peoples money of course.

**Comment by Noname400** [comment]
1. я когда то писал для brainflayer генератор. я посмотрю в архивах.
2. да на RUST все будет работать быстрее.
3. ........................

**Comment by PDOGEDEV** [comment]
1. Thanks :) 
2. Sounds good.
3. Thanks ;) could you upload it for me to download?

**Comment by Noname400** [comment]
BIP 49 восстанавливать не буду в новых версиях
в версии 3,6,1 он есть и работает корректно
https://github.com/Noname400/Hunt-to-Mnemonic/releases/tag/v3.6.1
проверьте через -e 1 и -e 2

**Comment by PDOGEDEV** [comment]
> BIP 49 восстанавливать не буду в новых версиях
> в версии 3,6,1 он есть и работает корректно
> https://github.com/Noname400/Hunt-to-Mnemonic/releases/tag/v3.6.1
> проверьте через -e 1 и -e 2

What is changed since this release?
Also, how did you choose/find addresses? In brainflayer BTC have over 20 million addresses, how about you? If your old version that is compatible with brainflayer is faster, why not use that?

**Comment by Noname400** [comment]
1. по поиску немного изменилось. изменения коснулись структуры кода, функционала, распределения памяти.
2. в базе 32.bf более 30млн адресов. а базе 44 белее 50млн. адресов (фильтра обновляю раз в месяц)
3. работы моей программы и брайнфлайера совсем разные. (https://learnmeabitcoin.com/technical/mnemonic), брайнфлайев работает с паролями и из них генерирует SEED фразу. я генерирую из мнемоники SEED фразу.

**Comment by PDOGEDEV** [comment]
I ask you to please reconsider adding eth again to make your tool as complete as possible. I dont understand how eth is different than the other coins when it comes to finding lost treasures.

**Comment by Noname400** [comment]
Сейчас программа может вести поиск по монетам ETH и ETC. 
Если говорить о потерянных сокровищах что на каждой монете есть потерянные кошельки, вот их мы и ищем

Если я вас не правильно понял, прошу уточнить свой вопрос

**Comment by PDOGEDEV** [comment]
I thought that you said that you removed eth from the current version, did I misunderstand? what is it that you removed? and how come all wallets are lost? the filters include active wallets as well right?

**Comment by Noname400** [comment]
я удалил возможность искать по адресам BIP49 
да фильтры содержать все доступные кошельки с балансами на момент создания базы

**Comment by PDOGEDEV** [comment]
Ok, I do not completely understand regarding BIP49, what can we find there? I thought it was ether?

**Comment by Noname400** [comment]
ETH есть только в BIP44, в BIP 49 были BTC, BTC SV, BTC CASH, LTC (например в BIP49 адрес BTC начинается с bc1, LTC начинается с M, BTC CASH начинается с q)

ложное срабатывание это когда попадание было где-то рядом.
BTC 18 это значит он нашел адрес 18 по счету из 20 (https://iancoleman.io/bip39/)
перебор ведется по первым 20 адресам в мнемонике

**Comment by PDOGEDEV** [comment]
ETH is in b-44 too? but -b 44 is also for searching BTC, BTC SV, BTC CASH, LTC correct? and the command for eth is now -b eth so how can it be 44 too?

When I read what you just wrote I understand it that you removed BTC, BTC SV, BTC CASH, LTC but that is not correct right?

Could you in simple terms explain, for BTC, BTC SV, BTC CASH, LTC you use -m s and -b 44 right?

For eth you use -m s and -b eth correct?

Then I still dont really understand what was removed with -b 49

**Comment by PDOGEDEV** [comment]
Regarding false positive, is it enough to just check the address on block explorer and if it was empty then its a false positive and no more checking is needed?

**Comment by Noname400** [comment]
Да конечно достаточно.
в 3,9 сделаю запрос баланса. будет проще.

**Comment by PDOGEDEV** [comment]
that sounds good, please check the question above too

**Comment by PDOGEDEV** [comment]
And is BIP32 bitcoin only?

Will BIP32 search more extensively for BTC? And you might miss those addresses with BIP44?

**Comment by Noname400** [comment]
> ETH тоже есть в В-44? но -b 44 также предназначен для поиска BTC, BTC SV, BTC CASH, LTC правильно? а команда для eth теперь -b eth, так как же она может быть 44?
> 
> Когда я прочитал то, что вы только что написали, я понял, что вы удалили BTC, BTC SV, BTC CASH, LTC, но это неправильно, верно?
> 
> Не могли бы вы простыми словами объяснить, что для BTC, BTC SV, BTC CASH, LTC вы правильно используете -ms и -b 44?
> 
> Для eth вы правильно используете -ms и -b eth?
> 
> Тогда я до сих пор не очень понимаю, что было удалено с помощью -b 49

1. да ETH&ETC тоже BIP44 но их пришлось отделить в отдельный поиск из-за большой базы. база содержит более 50 млн. адресов. помните что каждый поток загружает базу еще раз. поэтому ETH&ETC я выделил отдельно.
2.  BTC, BTC SV, BTC CASH, LTC - я убрал только BIP49 (например, в BIP49 адрес BTC начинается с bc1, LTC начинается с M, BTC CASH начинается с q))
3. BIP49 это совсем другие адреса
![image](https://user-images.githubusercontent.com/74019756/127020201-9ff8c786-1abb-40c5-8fb5-94ce8333bc7b.png)
Обратите внимание сюда:
![image](https://user-images.githubusercontent.com/74019756/127020440-8b4f4ba5-b97d-402a-9b03-8108aed1eee8.png)

**Comment by Noname400** [comment]
![image](https://user-images.githubusercontent.com/74019756/127020576-1618bbb9-0ea2-4328-9f24-07692076103d.png)
![image](https://user-images.githubusercontent.com/74019756/127020615-af38ebb0-0e75-45e6-8c0b-2859c30c064d.png)

**Comment by PDOGEDEV** [comment]
So the reason for removing 49 is because of database size and speed?

**Comment by PDOGEDEV** [comment]
Anyway, I have two wishes.

One is to make it faster, how much faster do you think rust will make it?

Two is that I would really like to be able to use my own wordlist

**Comment by Noname400** [comment]
> So the reason for removing 49 is because of database size and speed? and perhaps because it is not used very much?
> 
> How about 32? will searching in 32 find more BTC results than searching only 44? because of the more paths?

найти что-то это реально как найти сокровище. шанс найти 0,0000000001%

**Comment by Noname400** [comment]
> Anyway, I have two wishes.
> 
> One is to make it faster, how much faster do you think rust will make it?
> 
> Two is that I would really like to be able to use my own wordlist

Переводить на RUST еще рано, не готова логика программы.
использовать ваш список слов я могу помочь

**Comment by PDOGEDEV** [comment]
> > Anyway, I have two wishes.
> > One is to make it faster, how much faster do you think rust will make it?
> > Two is that I would really like to be able to use my own wordlist
> 
> Переводить на RUST еще рано, не готова логика программы.
> использовать ваш список слов я могу помочь

I would like to be able to experiment with different wordlist, could we add support for custom wordlist.txt?

**Comment by PDOGEDEV** [comment]
Another question: would a valid 12 word seed created as a plain brain wallet generate a completely different address? for example if you would feed brainflayer with generated 12 word seeds?

**Comment by Noname400** [comment]
> Другой вопрос: будет ли действительное семя из 12 слов, созданное как обычный мозговой кошелек, генерировать совершенно другой адрес? например, если бы вы накормили укротителя мозгов сгенерированными семенами из 12 слов?

очень мало вероятно

**Comment by PDOGEDEV** [comment]
How much work would it be to add a custom wordlist? can you support input for wordlist.txt?

**Comment by Noname400** [comment]
Загрузите ваш список слов

**Comment by PDOGEDEV** [comment]
> Загрузите ваш список слов

Well I want to try many different, perhaps firstly just the first 5 words of each word in the english list

**Comment by 233m** [comment]
@Noname400 
Привет. А я вот не понял. Ты пишешь что ищет по 20ти монетам. А в редми создавать базу адресов надо только для btc. 
Чет я не понимаю. Как реализована работа? куда-то шлется запросы в инет?

**Comment by Noname400** [comment]
Привет. на редмии нехватает времени, не успеваю дополнить . но если вы посмотрите на мой [диск ](https://drive.google.com/drive/folders/1oBMNxqwyYqp6Dx1q5j6erajf9wahGAda?usp=sharing) То там не только БТЦ

Еще сильно влияет в каком режиме вы ищите. если 32 то там только БТЦ и тащить туда базу с другими валютами смысла нет.
а вот если 44 тогда да 
все валюты по которым он ищет находятся в файле const.py
вот код:
```
    PATHS_44_49:dict = {
        "BTC": {"CODE":"0","PK":b'\x00',"PS":b'\x05'},
        "BCH": "145",
        "BSV": "236",
        "BTG": "156",
        "BTCZ": "177",
        "BITG": "222",
        "LCC": "192",
        "LTC": "2",
        "DOGE": "3",
        "DASH": "5",
        "NMC": "7",
        "FTC": "8",
        "DGB": "20",
        "MONA": "22",
        "VTC": "28",
        "XMY": "90",
        "ZEC": "133",
        "ZCL": "147",
        "QTUM": "2301",
        "RVN": "175",
        "FLO": "216"
    }
```
я думаю с обозначениями разберетесь.
Насчет отправки, никакие данные без вашего ведома не отправляются. (установите -st no)
вообще эта функция задумана для статистики если у вас работает более 1 компа (как у меня)
и данные которые идут в ситеме типа ключей мнемоник и сидов там не отправляются
функция реализована в funcP.py
```
    uid = str(inf.uid).encode('utf-8')
    name = email.desc.encode('utf-8')
    mode = str(inf.bip).encode('utf-8')
    thread = str(inf.th).encode('utf-8')
    speed = str(speed).encode('utf-8')
    total = str(total).encode('utf-8')
    found = str(found).encode('utf-8')
    time_t = datetime.datetime.now()
    time_b = time_t.strftime("%y/%m/%d %H:%M").encode('utf-8')
    ver = inf.version
    work = b'Worker online'
```
вот даные которые передаются:
UID - юид машины для того что бы отличать машины друг от друга, 
NAME - имя которое вы задаете при запуске (-des) по умолчанию local - это надо если на одной машине запущено несколько програм в разных режимах что бы их не путать
MODE - режим работы клиента (32,44,ETH)
THREAD - количество процесов
SPEED - скорость
TOTAL - сколько ключей уже перебрано
FOUND - сколько найдено
TIME_T и TIME_B это учет времени
VER - версия клиента
WORK - текст

вот и все.

Если есть еще вопросы задавайте., буду рад помочь.

**Comment by Noname400** [comment]
> > Загрузите ваш список слов
> 
> Ну, я хочу попробовать много разных, возможно, сначала только первые 5 слов каждого слова в английском списке

я постараюсь реализовать это в ближайших релизах

**Comment by 233m** [comment]
@Noname400 спасибо за ответ. А вот ты пишешь:
 _а вот если 44 тогда да_

Получается надо такую команду:
python3 PulsarMT2-hash.py -b BIP44 -db BF/work.bf -th 2 -m s -bit 128 -em no -sc no
что за ключи команды я понимаю. 

Основной вопрос в файле BF/work.bf  , в него можно помещать все адреса от 20-ти монет? (естественно в hash160) И тогда твоя прога будет гонять по всем монетам?

**Comment by Noname400** [comment]
Надо (-b 44) 

Да все адреса. И будет искать вовсе сразу

**Comment by 233m** [comment]
> 
> 
> Надо (-b 44)
> 
> Да все адреса. И будет искать вовсе сразу

Да, круто ты замутил. Посмотрел твой диск, глянул несколько разных монет, и по их адресам там какие-то копейки, либо пусто. В этом есть какой-то скрытый смысл?

**Comment by Noname400** [comment]
базы буду пересоздавать. так как когда их парсил выдрал все адреса включая пустые.
думаю на след неделе займусь. но примерно 80 % там с балансами.
но ини небольшие так что на производительность сильно не влияют.
если их не будешь добавлять то желательно исключить из поиска.
если надо я поясню как это сделать
вообще настройка простая:
1. выбрать языки
2. добавить их в программу
3. выбрать валюты
4. добавить или удалить в программе

**Comment by 233m** [comment]
> 
> 
> базы буду пересоздавать. так как когда их парсил выдрал все адреса включая пустые.
> думаю на след неделе займусь. но примерно 80 % там с балансами.
> но ини небольшие так что на производительность сильно не влияют.
> если их не будешь добавлять то желательно исключить из поиска.
> если надо я поясню как это сделать
> вообще настройка простая:
> 
>     1. выбрать языки
> 
>     2. добавить их в программу
> 
>     3. выбрать валюты
> 
>     4. добавить или удалить в программе

Язык тут определяем?
   mnemonic_lang = ['english']
   а монеты какие искать где-то тут?
l44 = [Bip44Coins.BITCOIN,Bip44Coins.BITCOIN_CASH,Bip44Coins.BITCOIN_SV,Bip44Coins.LITECOIN,Bip44Coins.DASH,Bip44Coins.DOGECOIN,Bip44Coins.ZCASH]
    l44_ = [b"\x00",b"\x00",b"\x00",b"\x30",b"\x4c",b"\x1e",b"\x1c\xb8"]
    l44__ = [Bip44Changes.CHAIN_EXT,Bip44Changes.CHAIN_INT]
    leth = [Bip44Coins.ETHEREUM,Bip44Coins.ETHEREUM_CLASSIC]
    l49 = [Bip44Coins.BITCOIN,Bip44Coins.BITCOIN_CASH,Bip44Coins.BITCOIN_SV,Bip44Coins.LITECOIN,Bip44Coins.DOGECOIN,Bip44Coins.ZCASH]
    l49_ = [b"\x05",b"\x05",b"\x05",b"\x32",b"\x16",b"\x1c\xbd"]

**Comment by Noname400** [comment]
Не совсем. Вы используете версию 3. Качайте 4

**Comment by 233m** [comment]
> 
> 
> Не совсем. Вы используете версию 3. Качайте 4

так это я из четвертой и привел.  качал отсюда - https://github.com/Noname400/Hunt-to-Mnemonic/releases/tag/v4.0.b2
сорс код, ну а потом пип инсталл .....

**Comment by Noname400** [comment]
Видемо путаница у вас. Код который привели выше из версии 3

**Comment by Noname400** [comment]
Для работы нужны 3 файла и они все в одной папке.

**Comment by 233m** [comment]
> 
> 
> Для работы нужны 3 файла и они все в одной папке.

хм. странно. посмотрю еще раз.

**Comment by 233m** [comment]
@Noname400 
я понял, надо было качать файлик nem3.zip
Правильно я понимаю, чтобы исключить монеты из перебора надо удалить их тут:
    PATHS_44_49:dict = {
        "BTC": {"CODE":"0","PK":b'\x00',"PS":b'\x05'},
        "BCH": "145",
        "BSV": "236",
        "BTG": "156",
        "BTCZ": "177",
        "BITG": "222",
        "LCC": "192",
        "LTC": "2",
        "DOGE": "3",
        "DASH": "5",
        "NMC": "7",
        "FTC": "8",
        "DGB": "20",
        "MONA": "22",
        "VTC": "28",
        "XMY": "90",
        "ZEC": "133",
        "ZCL": "147",
        "QTUM": "2301",
        "RVN": "175",
        "FLO": "216"
    }

**Comment by 233m** [comment]
@Noname400 
И правильно я понимаю что из списка BTC адресов можно удалять все кроме тех что с 1 начинаются? т.к. другие адреса это BIP49 и BIP84

**Comment by Noname400** [comment]
> @Noname400
> я понял, надо было качать файлик nem3.zip
> Правильно я понимаю, чтобы исключить монеты из перебора надо удалить их тут:
> l44:list = ["0","145","236","2","3","5","133","147","175","20"]
> И в списке нет ETH. с ним не работает?
> он по BIP44 не работает?

да верно понимаете
ЕТН я вынес в отдельный режим так как у него адрес другого формата

**Comment by Noname400** [comment]
> @Noname400
> И правильно я понимаю что из списка BTC адресов можно удалять все кроме тех что с 1 начинаются? т.к. другие адреса это BIP49 и BIP84

да все верно.!

**Comment by 233m** [comment]
круто. спасибо за пояснения!
