### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by VuzzyM** [Noname400/Hunt-to-Mnemonic#8]
Привет

Можете ли вы сделать программу которая работает точно так же как здесь?  Алгоритм должен быть таким же, как описано в статье, все материалы написаны в статье.

Спасибо за помощь

https://medium.com/@johncantrell97/how-i-checked-over-1-trillion-mnemonics-in-30-hours-to-win-a-bitcoin-635fe051a752

**Comment by Noname400** [comment]
Она уже сделана, зачем делать еще раз ?
https://github.com/johncantrell97/bip39-solver-gpu
https://github.com/johncantrell97/bip39-solver-cpu
https://github.com/johncantrell97/bip39-solver-gpu2

**Comment by VuzzyM** [comment]
@Noname400 Как мне его запустить?  Он сделан на языке Rust, а не python

https://github.com/johncantrell97/bip39-solver-cpu

**Comment by Noname400** [comment]
Вам необходимо открыть документацию на rust и посмотреть как он работает. я не смогу вам это объяснить есть вы никогда не занимались программированием.
Вы скажите почему и чем вас заинтересовал код от johncantrel ?

**Comment by VuzzyM** [comment]
> Вам необходимо открыть документацию на rust и посмотреть как он работает. я не смогу вам это объяснить есть вы никогда не занимались программированием.
> Вы скажите почему и чем вас заинтересовал код от johncantrel ?

сделать тот же скрипт на питоне, если возможно

**Comment by Noname400** [comment]
Вы можете пояснить что вы хотите?
какие данные есть на входе и что хотите получить на выходе ?
потому как моя программа делает примерно тоже самое с небольшими отличиями.
программа джона заточена на определенный адрес и у него на входе известно несколько слов
моя программа ищет по все известным адресам подбирая мнемонику. если у вас есть известные слова и адрес тогда вам лучше обратиться к проекту https://github.com/3rdIteration/btcrecover

**Comment by VuzzyM** [comment]
> Вы можете пояснить что вы хотите?
> какие данные есть на входе и что хотите получить на выходе ?
> потому как моя программа делает примерно тоже самое с небольшими отличиями.
> программа джона заточена на определенный адрес и у него на входе известно несколько слов
> моя программа ищет по все известным адресам подбирая мнемонику. если у вас есть известные слова и адрес тогда вам лучше обратиться к проекту https://github.com/3rdIteration/btcrecover

Хорошо, я понял, я воспользуюсь твоей программой
