### ISSUE TITLE
Запуск на windows?

### ISSUE THREAD

**Issue by Vladimir855** [Noname400/Hunt-to-Mnemonic#9]
Подскажите как запустить на windows? 
![Screenshot_47](https://user-images.githubusercontent.com/48643229/127294121-23f5b963-9fd8-4ea6-981d-bd4eba207ec3.png)

**Comment by Noname400** [comment]
Сдалайте pip list

**Comment by Noname400** [comment]
или могу для вас скомпилировать это в exe

**Comment by montarem** [comment]
Не могу запустить скрипт скачал ваши файл по ссылке и пишет вот это

* Version:  Pulsar v3.7.6b multiT Hash160
* Identificator system: b'00000000-0000-0000-0000-082e5f75983f'
* Total kernel of CPU: 4
* Used kernel: 2
* Mode Search: BIP-44 Standart
* Dir database Bloom Filter: BF
* Languages at work: ['english']
* Description Server: home
* Mode debug: Off
* Send mail: Off
* Send Statistic to server: Off

File: 44.bf not found.

File: 44.bf not found.

**Comment by Noname400** [comment]
Положите файлы бф в папку бф

**Comment by Noname400** [comment]
Dir database Bloom Filter: BF

**Comment by Vladimir855** [comment]
на слабом компе потянет, 2ядра 2 гига win7?  если можно скомпилировать это в exe

**Comment by Noname400** [comment]
да конечно

**Comment by Noname400** [comment]
> на слабом компе потянет, 2ядра 2 гига win7? если можно скомпилировать это в exe

сделаю сегодня
